# Connect Database

In [4]:
import os
import psycopg

conn = psycopg.connect(
    host=os.getenv("PGHOST", "localhost"),
    port=os.getenv("PGPORT", "5432"),
    dbname=os.getenv("PGDATABASE", "final"),
    user=os.getenv("PGUSER", "postgres"),
    password=os.getenv("PGPASSWORD")
)

In [ ]:
cur = conn.cursor()
print("Connected to PostgreSQL")

cur.execute("""
    DROP TABLE IF EXISTS daily_price;
    DROP TABLE IF EXISTS company;
""")

# Create Tech Company Table

In [3]:
cur.execute("""
    CREATE TABLE company (
        company_id      SERIAL PRIMARY KEY, 
        cik             VARCHAR(10) NOT NULL UNIQUE,
        ticker          VARCHAR(10) NOT NULL UNIQUE,
        company_name    TEXT NOT NULL,
        sic             INTEGER,
        sic_description TEXT
    );""")
conn.commit()
print("Table 'company' created.")

Table 'company' created.

In [4]:
import pandas as pd
df = pd.read_csv("company_list.csv")
df.head()

df_clean = df.rename(columns={
    "ticker": "ticker",
    "title": "company_name",
    "CIK": "cik",
    "SIC": "sic",
    "SIC_description": "sic_description"
})

# Convert CIK to 10 digits
df_clean["cik"] = df_clean["cik"].astype(str).str.zfill(10)
df_clean.head()

,ticker,company_name,cik,sic,sic_description
0,BKTI,BK Technologies Corp,0000002186,3663,Radio & Tv Broadcasting & Communications Equip...
1,AMD,ADVANCED MICRO DEVICES INC,0000002488,3674,Semiconductors & Related Devices
2,SWKS,"SKYWORKS SOLUTIONS, INC.",0000004127,3674,Semiconductors & Related Devices
3,ADI,ANALOG DEVICES INC,0000006281,3674,Semiconductors & Related Devices
4,AMAT,APPLIED MATERIALS INC /DE,0000006951,3674,Semiconductors & Related Devices

In [5]:
for _, row in df_clean.iterrows():
    cur.execute("""
        INSERT INTO company (cik, ticker, company_name, sic, sic_description)
        VALUES (%s, %s, %s, %s, %s);
    """, (
        row["cik"],
        row["ticker"],
        row["company_name"],
        int(row["sic"]) if not pd.isna(row["sic"]) else None,
        row["sic_description"]
    ))

conn.commit()
print("All companies inserted!")

All companies inserted!

In [7]:
cur.execute("SELECT company_id, cik, ticker, company_name FROM company LIMIT 10;")
for row in cur.fetchall():
    print(row)
cur.execute("SELECT COUNT(*) FROM company;")
print("Total companies:", cur.fetchone()[0])

cur.execute("""
    SELECT
        COUNT(*) FILTER (WHERE cik IS NULL)              AS cik_nulls,
        COUNT(*) FILTER (WHERE ticker IS NULL)           AS ticker_nulls,
        COUNT(*) FILTER (WHERE company_name IS NULL)     AS company_name_nulls,
        COUNT(*) FILTER (WHERE sic IS NULL)              AS sic_nulls,
        COUNT(*) FILTER (WHERE sic_description IS NULL)  AS sic_description_nulls
    FROM company;
""")

print("NULL count per column:", cur.fetchone())

(1, '0000002186', 'BKTI', 'BK Technologies Corp')
(2, '0000002488', 'AMD', 'ADVANCED MICRO DEVICES INC')
(3, '0000004127', 'SWKS', 'SKYWORKS SOLUTIONS, INC.')
(4, '0000006281', 'ADI', 'ANALOG DEVICES INC')
(5, '0000006951', 'AMAT', 'APPLIED MATERIALS INC /DE')
(6, '0000008146', 'ALOT', 'AstroNova, Inc.')
(7, '0000008670', 'ADP', 'AUTOMATIC DATA PROCESSING INC')
(8, '0000016058', 'CACI', 'CACI INTERNATIONAL INC /DE/')
(9, '0000023197', 'CMTL', 'COMTECH TELECOMMUNICATIONS CORP /DE/')
(10, '0000026058', 'CTS', 'CTS CORP')
Total companies: 927
NULL count per column: (0, 0, 0, 0, 0)

# Create daily_price table & insert data from yahoo finance

In [1]:
!pip install -U "psycopg[binary]" yfinance pandas

Requirement already satisfied: yfinance in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (0.2.66)
Requirement already satisfied: pandas in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (2.3.3)
Requirement already satisfied: psycopg[binary] in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (3.2.13)
Requirement already satisfied: tzdata in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from psycopg[binary]) (2025.2)
Requirement already satisfied: psycopg-binary==3.2.13 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from psycopg[binary]) (3.2.13)
Requirement already satisfied: numpy>=1.16.5 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (2.3.2)
Requirement already satisfied: requests>=2.31 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (4.4.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (3.18.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (6.33.1)
Requirement already satisfied: websockets>=13.0 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (15.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: soupsieve>1.2 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from curl_cffi>=0.7->yfinance) (2025.8.3)
Requirement already satisfied: pycparser in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.22)
Requirement already satisfied: six>=1.5 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.31->yfinance) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.31->yfinance) (2.5.0)

WARNING: Ignoring invalid distribution ~andas (C:\Users\Milan_Chen\AppData\Local\Programs\Python\Python313\Lib\site-packages)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:

import psycopg

conn = psycopg.connect(
    host=os.getenv("PGHOST", "localhost"),
    port=os.getenv("PGPORT", "5432"),
    dbname=os.getenv("PGDATABASE", "final"),
    user=os.getenv("PGUSER", "postgres"),
    password=os.getenv("PGPASSWORD")
)
cur = conn.cursor()
print("Connected to Final database.")

Connected to Final database.

In [4]:
cur.execute("""
    DROP TABLE IF EXISTS daily_price;

    CREATE TABLE daily_price (
        company_id  INTEGER NOT NULL REFERENCES company(company_id),
        trade_date  DATE    NOT NULL,
        open        NUMERIC(18,4),
        high        NUMERIC(18,4),
        low         NUMERIC(18,4),
        close       NUMERIC(18,4),
        adj_close   NUMERIC(18,4),
        volume      BIGINT,
        PRIMARY KEY (company_id, trade_date)
    );
""")
conn.commit()

print("Table 'daily_price' created.")

Table 'daily_price' created.

In [5]:
import pandas as pd

df_comp = pd.read_sql("SELECT company_id, ticker FROM company ORDER BY company_id;", conn)

print("Total companies:", len(df_comp))
df_comp.head()

Total companies: 927

C:\Users\Milan_Chen\AppData\Local\Temp\ipykernel_53728\587111543.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_comp = pd.read_sql("SELECT company_id, ticker FROM company ORDER BY company_id;", conn)

   company_id ticker
0           1   BKTI
1           2    AMD
2           3   SWKS
3           4    ADI
4           5   AMAT

Set the starting point as November 28, 2015 and the ending point as today. Daily OHLCV of grabbing a certain ticker from FIXED_START to TODAY. Take as much as you have. If the company has been listed for less than ten years, the returned data will automatically decrease.

In [11]:
import yfinance as yf
from datetime import datetime

FIXED_START = "2015-11-28"                       
# fixed beginning date
TODAY = datetime.today().strftime("%Y-%m-%d")    
# end date = today

print("Fetching window:", FIXED_START, "→", TODAY)

def fetch_price_fixed_window(ticker: str):

    try:
        df = yf.download(
            ticker,
            start=FIXED_START,
            end=TODAY,
            auto_adjust=False,
            progress=False
        )

        if df.empty:
            print(f"⚠️ {ticker}: no price data found.")
            return None

        df.reset_index(inplace=True)

        df.rename(columns={
            "Date": "trade_date",
            "Open": "open",
            "High": "high",
            "Low": "low",
            "Close": "close",
            "Adj Close": "adj_close",
            "Volume": "volume"
        }, inplace=True)

        df = df[["trade_date", "open", "high", "low", "close", "adj_close", "volume"]]

        return df

    except Exception as e:
        print(f"❌ Error downloading {ticker}: {e}")
        return None

Fetching window: 2015-11-28 → 2025-11-28

rec is a tuple, corresponding to the column order:  
(trade_date, open, high, low, close, adj_close, volume)

In [12]:
import math

for _, row in df_comp.iterrows():
    cid = int(row["company_id"])
    ticker = row["ticker"]

    print(f"\nFetching from {FIXED_START} to {TODAY} for {ticker} (company_id={cid}) ...")

    df_price = fetch_price_fixed_window(ticker)
    if df_price is None:
        continue

    print("  Columns from yfinance:", list(df_price.columns))

    for rec in df_price.itertuples(index=False, name=None):
        
        trade_date_raw, open_raw, high_raw, low_raw, close_raw, adj_close_raw, vol_raw = rec

        if isinstance(trade_date_raw, pd.Timestamp):
            trade_date = trade_date_raw.date()
        else:
            trade_date = trade_date_raw

        def to_num(x):
            if x is None:
                return None
            if isinstance(x, float) and math.isnan(x):
                return None
            return float(x)

        open_      = to_num(open_raw)
        high_      = to_num(high_raw)
        low_       = to_num(low_raw)
        close_     = to_num(close_raw)
        adj_close_ = to_num(adj_close_raw)

        vol = vol_raw
        if vol is None or (isinstance(vol, float) and math.isnan(vol)):
            vol = None
        else:
            vol = int(vol)

        cur.execute("""
            INSERT INTO daily_price
                (company_id, trade_date, open, high, low, close, adj_close, volume)
            VALUES
                (%s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (company_id, trade_date) DO NOTHING;
        """, (
            cid,
            trade_date,
            open_,
            high_,
            low_,
            close_,
            adj_close_,
            vol
        ))

    conn.commit()
    print(f"✔ Inserted {len(df_price)} rows for {ticker}.")

⬇️ Fetching from 2015-11-28 to 2025-11-28 for BKTI (company_id=1) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'BKTI'), ('high', 'BKTI'), ('low', 'BKTI'), ('close', 'BKTI'), ('adj_close', 'BKTI'), ('volume', 'BKTI')]
✔ Inserted 2514 rows for BKTI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for AMD (company_id=2) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'AMD'), ('high', 'AMD'), ('low', 'AMD'), ('close', 'AMD'), ('adj_close', 'AMD'), ('volume', 'AMD')]
✔ Inserted 2514 rows for AMD.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for SWKS (company_id=3) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'SWKS'), ('high', 'SWKS'), ('low', 'SWKS'), ('close', 'SWKS'), ('adj_close', 'SWKS'), ('volume', 'SWKS')]
✔ Inserted 2514 rows for SWKS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ADI (company_id=4) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ADI'), ('high', 'ADI'), ('low', 'ADI'), ('close', 'ADI'), ('adj_close', 'ADI'), ('volume', 'ADI')]
✔ Inserted 2514 rows for ADI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for AMAT (company_id=5) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'AMAT'), ('high', 'AMAT'), ('low', 'AMAT'), ('close', 'AMAT'), ('adj_close', 'AMAT'), ('volume', 'AMAT')]
✔ Inserted 2514 rows for AMAT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ALOT (company_id=6) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ALOT'), ('high', 'ALOT'), ('low', 'ALOT'), ('close', 'ALOT'), ('adj_close', 'ALOT'), ('volume', 'ALOT')]
✔ Inserted 2514 rows for ALOT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ADP (company_id=7) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ADP'), ('high', 'ADP'), ('low', 'ADP'), ('close', 'ADP'), ('adj_close', 'ADP'), ('volume', 'ADP')]
✔ Inserted 2514 rows for ADP.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CACI (company_id=8) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CACI'), ('high', 'CACI'), ('low', 'CACI'), ('close', 'CACI'), ('adj_close', 'CACI'), ('volume', 'CACI')]
✔ Inserted 2514 rows for CACI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CMTL (company_id=9) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CMTL'), ('high', 'CMTL'), ('low', 'CMTL'), ('close', 'CMTL'), ('adj_close', 'CMTL'), ('volume', 'CMTL')]
✔ Inserted 2514 rows for CMTL.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CTS (company_id=10) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CTS'), ('high', 'CTS'), ('low', 'CTS'), ('close', 'CTS'), ('adj_close', 'CTS'), ('volume', 'CTS')]
✔ Inserted 2514 rows for CTS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for DBD (company_id=11) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'DBD'), ('high', 'DBD'), ('low', 'DBD'), ('close', 'DBD'), ('adj_close', 'DBD'), ('volume', 'DBD')]
✔ Inserted 576 rows for DBD.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for DIOD (company_id=12) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'DIOD'), ('high', 'DIOD'), ('low', 'DIOD'), ('close', 'DIOD'), ('adj_close', 'DIOD'), ('volume', 'DIOD')]
✔ Inserted 2514 rows for DIOD.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ESP (company_id=13) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ESP'), ('high', 'ESP'), ('low', 'ESP'), ('close', 'ESP'), ('adj_close', 'ESP'), ('volume', 'ESP')]
✔ Inserted 2514 rows for ESP.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for FELE (company_id=14) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'FELE'), ('high', 'FELE'), ('low', 'FELE'), ('close', 'FELE'), ('adj_close', 'FELE'), ('volume', 'FELE')]
✔ Inserted 2514 rows for FELE.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for HPQ (company_id=15) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'HPQ'), ('high', 'HPQ'), ('low', 'HPQ'), ('close', 'HPQ'), ('adj_close', 'HPQ'), ('volume', 'HPQ')]
✔ Inserted 2514 rows for HPQ.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for HUBB (company_id=16) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'HUBB'), ('high', 'HUBB'), ('low', 'HUBB'), ('close', 'HUBB'), ('adj_close', 'HUBB'), ('volume', 'HUBB')]
✔ Inserted 2514 rows for HUBB.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for IEHC (company_id=17) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'IEHC'), ('high', 'IEHC'), ('low', 'IEHC'), ('close', 'IEHC'), ('adj_close', 'IEHC'), ('volume', 'IEHC')]
✔ Inserted 2514 rows for IEHC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TRAK (company_id=18) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TRAK'), ('high', 'TRAK'), ('low', 'TRAK'), ('close', 'TRAK'), ('adj_close', 'TRAK'), ('volume', 'TRAK')]
✔ Inserted 2514 rows for TRAK.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for INTC (company_id=19) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'INTC'), ('high', 'INTC'), ('low', 'INTC'), ('close', 'INTC'), ('adj_close', 'INTC'), ('volume', 'INTC')]
✔ Inserted 2514 rows for INTC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for IBM (company_id=20) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'IBM'), ('high', 'IBM'), ('low', 'IBM'), ('close', 'IBM'), ('adj_close', 'IBM'), ('volume', 'IBM')]
✔ Inserted 2514 rows for IBM.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for KLIC (company_id=21) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'KLIC'), ('high', 'KLIC'), ('low', 'KLIC'), ('close', 'KLIC'), ('adj_close', 'KLIC'), ('volume', 'KLIC')]
✔ Inserted 2514 rows for KLIC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for LGL (company_id=22) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'LGL'), ('high', 'LGL'), ('low', 'LGL'), ('close', 'LGL'), ('adj_close', 'LGL'), ('volume', 'LGL')]
✔ Inserted 2514 rows for LGL.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for MEI (company_id=23) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'MEI'), ('high', 'MEI'), ('low', 'MEI'), ('close', 'MEI'), ('adj_close', 'MEI'), ('volume', 'MEI')]
✔ Inserted 2514 rows for MEI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for MVIS (company_id=24) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'MVIS'), ('high', 'MVIS'), ('low', 'MVIS'), ('close', 'MVIS'), ('adj_close', 'MVIS'), ('volume', 'MVIS')]
✔ Inserted 2514 rows for MVIS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for MSI (company_id=25) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'MSI'), ('high', 'MSI'), ('low', 'MSI'), ('close', 'MSI'), ('adj_close', 'MSI'), ('volume', 'MSI')]
✔ Inserted 2514 rows for MSI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for NSSC (company_id=26) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'NSSC'), ('high', 'NSSC'), ('low', 'NSSC'), ('close', 'NSSC'), ('adj_close', 'NSSC'), ('volume', 'NSSC')]
✔ Inserted 2514 rows for NSSC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for VYX (company_id=27) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'VYX'), ('high', 'VYX'), ('low', 'VYX'), ('close', 'VYX'), ('adj_close', 'VYX'), ('volume', 'VYX')]
✔ Inserted 2514 rows for VYX.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for AGYS (company_id=28) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'AGYS'), ('high', 'AGYS'), ('low', 'AGYS'), ('close', 'AGYS'), ('adj_close', 'AGYS'), ('volume', 'AGYS')]
✔ Inserted 2514 rows for AGYS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for PBI (company_id=29) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'PBI'), ('high', 'PBI'), ('low', 'PBI'), ('close', 'PBI'), ('adj_close', 'PBI'), ('volume', 'PBI')]
✔ Inserted 2514 rows for PBI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for RSKIA (company_id=30) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'RSKIA'), ('high', 'RSKIA'), ('low', 'RSKIA'), ('close', 'RSKIA'), ('adj_close', 'RSKIA'), ('volume', 'RSKIA')]
✔ Inserted 2514 rows for RSKIA.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for NEON (company_id=31) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'NEON'), ('high', 'NEON'), ('low', 'NEON'), ('close', 'NEON'), ('adj_close', 'NEON'), ('volume', 'NEON')]
✔ Inserted 2514 rows for NEON.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for SMTC (company_id=32) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'SMTC'), ('high', 'SMTC'), ('low', 'SMTC'), ('close', 'SMTC'), ('adj_close', 'SMTC'), ('volume', 'SMTC')]
✔ Inserted 2514 rows for SMTC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for SODI (company_id=33) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'SODI'), ('high', 'SODI'), ('low', 'SODI'), ('close', 'SODI'), ('adj_close', 'SODI'), ('volume', 'SODI')]
✔ Inserted 2514 rows for SODI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TIKK (company_id=34) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TIKK'), ('high', 'TIKK'), ('low', 'TIKK'), ('close', 'TIKK'), ('adj_close', 'TIKK'), ('volume', 'TIKK')]
✔ Inserted 2514 rows for TIKK.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TXN (company_id=35) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TXN'), ('high', 'TXN'), ('low', 'TXN'), ('close', 'TXN'), ('adj_close', 'TXN'), ('volume', 'TXN')]
✔ Inserted 2514 rows for TXN.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for VSH (company_id=36) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'VSH'), ('high', 'VSH'), ('low', 'VSH'), ('close', 'VSH'), ('adj_close', 'VSH'), ('volume', 'VSH')]
✔ Inserted 2514 rows for VSH.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for WDC (company_id=37) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'WDC'), ('high', 'WDC'), ('low', 'WDC'), ('close', 'WDC'), ('adj_close', 'WDC'), ('volume', 'WDC')]
✔ Inserted 2514 rows for WDC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for WWD (company_id=38) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'WWD'), ('high', 'WWD'), ('low', 'WWD'), ('close', 'WWD'), ('adj_close', 'WWD'), ('volume', 'WWD')]
✔ Inserted 2514 rows for WWD.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for PSN (company_id=39) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'PSN'), ('high', 'PSN'), ('low', 'PSN'), ('close', 'PSN'), ('adj_close', 'PSN'), ('volume', 'PSN')]
✔ Inserted 1650 rows for PSN.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for OMQS (company_id=40) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'OMQS'), ('high', 'OMQS'), ('low', 'OMQS'), ('close', 'OMQS'), ('adj_close', 'OMQS'), ('volume', 'OMQS')]
✔ Inserted 2514 rows for OMQS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TLS (company_id=41) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TLS'), ('high', 'TLS'), ('low', 'TLS'), ('close', 'TLS'), ('adj_close', 'TLS'), ('volume', 'TLS')]
✔ Inserted 1261 rows for TLS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for AAPL (company_id=42) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'AAPL'), ('high', 'AAPL'), ('low', 'AAPL'), ('close', 'AAPL'), ('adj_close', 'AAPL'), ('volume', 'AAPL')]
✔ Inserted 2514 rows for AAPL.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CSPI (company_id=43) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CSPI'), ('high', 'CSPI'), ('low', 'CSPI'), ('close', 'CSPI'), ('adj_close', 'CSPI'), ('volume', 'CSPI')]
✔ Inserted 2514 rows for CSPI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for PAR (company_id=44) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'PAR'), ('high', 'PAR'), ('low', 'PAR'), ('close', 'PAR'), ('adj_close', 'PAR'), ('volume', 'PAR')]
✔ Inserted 2514 rows for PAR.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for QMCO (company_id=45) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'QMCO'), ('high', 'QMCO'), ('low', 'QMCO'), ('close', 'QMCO'), ('adj_close', 'QMCO'), ('volume', 'QMCO')]
✔ Inserted 2514 rows for QMCO.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for EA (company_id=46) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'EA'), ('high', 'EA'), ('low', 'EA'), ('close', 'EA'), ('adj_close', 'EA'), ('volume', 'EA')]
✔ Inserted 2514 rows for EA.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ERIC (company_id=47) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ERIC'), ('high', 'ERIC'), ('low', 'ERIC'), ('close', 'ERIC'), ('adj_close', 'ERIC'), ('volume', 'ERIC')]
✔ Inserted 2514 rows for ERIC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for KTCC (company_id=48) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'KTCC'), ('high', 'KTCC'), ('low', 'KTCC'), ('close', 'KTCC'), ('adj_close', 'KTCC'), ('volume', 'KTCC')]
✔ Inserted 2514 rows for KTCC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for NSYS (company_id=49) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'NSYS'), ('high', 'NSYS'), ('low', 'NSYS'), ('close', 'NSYS'), ('adj_close', 'NSYS'), ('volume', 'NSYS')]
✔ Inserted 2514 rows for NSYS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for FKWL (company_id=50) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'FKWL'), ('high', 'FKWL'), ('low', 'FKWL'), ('close', 'FKWL'), ('adj_close', 'FKWL'), ('volume', 'FKWL')]
✔ Inserted 2514 rows for FKWL.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for MU (company_id=51) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'MU'), ('high', 'MU'), ('low', 'MU'), ('close', 'MU'), ('adj_close', 'MU'), ('volume', 'MU')]
✔ Inserted 2514 rows for MU.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for NVEC (company_id=52) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'NVEC'), ('high', 'NVEC'), ('low', 'NVEC'), ('close', 'NVEC'), ('adj_close', 'NVEC'), ('volume', 'NVEC')]
✔ Inserted 2514 rows for NVEC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for BELFA (company_id=53) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'BELFA'), ('high', 'BELFA'), ('low', 'BELFA'), ('close', 'BELFA'), ('adj_close', 'BELFA'), ('volume', 'BELFA')]
✔ Inserted 2514 rows for BELFA.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for RAMP (company_id=54) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'RAMP'), ('high', 'RAMP'), ('low', 'RAMP'), ('close', 'RAMP'), ('adj_close', 'RAMP'), ('volume', 'RAMP')]
✔ Inserted 2514 rows for RAMP.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for INTZ (company_id=55) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'INTZ'), ('high', 'INTZ'), ('low', 'INTZ'), ('close', 'INTZ'), ('adj_close', 'INTZ'), ('volume', 'INTZ')]
✔ Inserted 2514 rows for INTZ.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for RFIL (company_id=56) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'RFIL'), ('high', 'RFIL'), ('low', 'RFIL'), ('close', 'RFIL'), ('adj_close', 'RFIL'), ('volume', 'RFIL')]
✔ Inserted 2514 rows for RFIL.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for OBLG (company_id=57) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'OBLG'), ('high', 'OBLG'), ('low', 'OBLG'), ('close', 'OBLG'), ('adj_close', 'OBLG'), ('volume', 'OBLG')]
✔ Inserted 2514 rows for OBLG.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for UIS (company_id=58) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'UIS'), ('high', 'UIS'), ('low', 'UIS'), ('close', 'UIS'), ('adj_close', 'UIS'), ('volume', 'UIS')]
✔ Inserted 2514 rows for UIS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for RCAT (company_id=59) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'RCAT'), ('high', 'RCAT'), ('low', 'RCAT'), ('close', 'RCAT'), ('adj_close', 'RCAT'), ('volume', 'RCAT')]
✔ Inserted 2514 rows for RCAT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for LNW (company_id=60) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'LNW'), ('high', 'LNW'), ('low', 'LNW'), ('close', 'LNW'), ('adj_close', 'LNW'), ('volume', 'LNW')]
✔ Inserted 2514 rows for LNW.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for VICR (company_id=61) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'VICR'), ('high', 'VICR'), ('low', 'VICR'), ('close', 'VICR'), ('adj_close', 'VICR'), ('volume', 'VICR')]
✔ Inserted 2514 rows for VICR.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ADSK (company_id=62) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ADSK'), ('high', 'ADSK'), ('low', 'ADSK'), ('close', 'ADSK'), ('adj_close', 'ADSK'), ('volume', 'ADSK')]
✔ Inserted 2514 rows for ADSK.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for KOPN (company_id=63) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'KOPN'), ('high', 'KOPN'), ('low', 'KOPN'), ('close', 'KOPN'), ('adj_close', 'KOPN'), ('volume', 'KOPN')]
✔ Inserted 2514 rows for KOPN.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CRUS (company_id=64) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CRUS'), ('high', 'CRUS'), ('low', 'CRUS'), ('close', 'CRUS'), ('adj_close', 'CRUS'), ('volume', 'CRUS')]
✔ Inserted 2514 rows for CRUS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for JKHY (company_id=65) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'JKHY'), ('high', 'JKHY'), ('low', 'JKHY'), ('close', 'JKHY'), ('adj_close', 'JKHY'), ('volume', 'JKHY')]
✔ Inserted 2514 rows for JKHY.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for PLXS (company_id=66) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'PLXS'), ('high', 'PLXS'), ('low', 'PLXS'), ('close', 'PLXS'), ('adj_close', 'PLXS'), ('volume', 'PLXS')]
✔ Inserted 2514 rows for PLXS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for MSFT (company_id=67) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'MSFT'), ('high', 'MSFT'), ('low', 'MSFT'), ('close', 'MSFT'), ('adj_close', 'MSFT'), ('volume', 'MSFT')]
✔ Inserted 2514 rows for MSFT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CONC (company_id=68) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CONC'), ('high', 'CONC'), ('low', 'CONC'), ('close', 'CONC'), ('adj_close', 'CONC'), ('volume', 'CONC')]
✔ Inserted 2514 rows for CONC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ADBE (company_id=69) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ADBE'), ('high', 'ADBE'), ('low', 'ADBE'), ('close', 'ADBE'), ('adj_close', 'ADBE'), ('volume', 'ADBE')]
✔ Inserted 2514 rows for ADBE.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CLFD (company_id=70) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CLFD'), ('high', 'CLFD'), ('low', 'CLFD'), ('close', 'CLFD'), ('adj_close', 'CLFD'), ('volume', 'CLFD')]
✔ Inserted 2514 rows for CLFD.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for VBIX (company_id=71) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'VBIX'), ('high', 'VBIX'), ('low', 'VBIX'), ('close', 'VBIX'), ('adj_close', 'VBIX'), ('volume', 'VBIX')]
✔ Inserted 2514 rows for VBIX.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for MITI (company_id=72) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'MITI'), ('high', 'MITI'), ('low', 'MITI'), ('close', 'MITI'), ('adj_close', 'MITI'), ('volume', 'MITI')]
✔ Inserted 2514 rows for MITI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for AIFF (company_id=73) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'AIFF'), ('high', 'AIFF'), ('low', 'AIFF'), ('close', 'AIFF'), ('adj_close', 'AIFF'), ('volume', 'AIFF')]
✔ Inserted 2514 rows for AIFF.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for QCOM (company_id=74) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'QCOM'), ('high', 'QCOM'), ('low', 'QCOM'), ('close', 'QCOM'), ('adj_close', 'QCOM'), ('volume', 'QCOM')]
✔ Inserted 2514 rows for QCOM.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for MITK (company_id=75) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'MITK'), ('high', 'MITK'), ('low', 'MITK'), ('close', 'MITK'), ('adj_close', 'MITK'), ('volume', 'MITK')]
✔ Inserted 2514 rows for MITK.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for PLAB (company_id=76) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'PLAB'), ('high', 'PLAB'), ('low', 'PLAB'), ('close', 'PLAB'), ('adj_close', 'PLAB'), ('volume', 'PLAB')]
✔ Inserted 2514 rows for PLAB.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CDNS (company_id=77) ...

1 Failed download:
['CAST']: YFPricesMissingError('possibly delisted; no price data found  (1d 2015-11-28 -> 2025-11-28)')

⚠️ CAST: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for LITE (company_id=506) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'LITE'), ('high', 'LITE'), ('low', 'LITE'), ('close', 'LITE'), ('adj_close', 'LITE'), ('volume', 'LITE')]
✔ Inserted 2514 rows for LITE.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for FLUT (company_id=507) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'FLUT'), ('high', 'FLUT'), ('low', 'FLUT'), ('close', 'FLUT'), ('adj_close', 'FLUT'), ('volume', 'FLUT')]
✔ Inserted 2514 rows for FLUT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for HCAT (company_id=508) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'HCAT'), ('high', 'HCAT'), ('low', 'HCAT'), ('close', 'HCAT'), ('adj_close', 'HCAT'), ('volume', 'HCAT')]
✔ Inserted 1596 rows for HCAT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ZSPC (company_id=509) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ZSPC'), ('high', 'ZSPC'), ('low', 'ZSPC'), ('close', 'ZSPC'), ('adj_close', 'ZSPC'), ('volume', 'ZSPC')]
✔ Inserted 245 rows for ZSPC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TTAN (company_id=510) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TTAN'), ('high', 'TTAN'), ('low', 'TTAN'), ('close', 'TTAN'), ('adj_close', 'TTAN'), ('volume', 'TTAN')]
✔ Inserted 240 rows for TTAN.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for NAVN (company_id=511) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'NAVN'), ('high', 'NAVN'), ('low', 'NAVN'), ('close', 'NAVN'), ('adj_close', 'NAVN'), ('volume', 'NAVN')]
✔ Inserted 20 rows for NAVN.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for SNOW (company_id=512) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'SNOW'), ('high', 'SNOW'), ('low', 'SNOW'), ('close', 'SNOW'), ('adj_close', 'SNOW'), ('volume', 'SNOW')]
✔ Inserted 1307 rows for SNOW.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for EVER (company_id=513) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'EVER'), ('high', 'EVER'), ('low', 'EVER'), ('close', 'EVER'), ('adj_close', 'EVER'), ('volume', 'EVER')]
✔ Inserted 1865 rows for EVER.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for IOT (company_id=514) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'IOT'), ('high', 'IOT'), ('low', 'IOT'), ('close', 'IOT'), ('adj_close', 'IOT'), ('volume', 'IOT')]
✔ Inserted 992 rows for IOT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for NNDM (company_id=515) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'NNDM'), ('high', 'NNDM'), ('low', 'NNDM'), ('close', 'NNDM'), ('adj_close', 'NNDM'), ('volume', 'NNDM')]
✔ Inserted 2448 rows for NNDM.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for WBSR (company_id=516) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'WBSR'), ('high', 'WBSR'), ('low', 'WBSR'), ('close', 'WBSR'), ('adj_close', 'WBSR'), ('volume', 'WBSR')]
✔ Inserted 1087 rows for WBSR.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for HPE (company_id=517) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'HPE'), ('high', 'HPE'), ('low', 'HPE'), ('close', 'HPE'), ('adj_close', 'HPE'), ('volume', 'HPE')]
✔ Inserted 2514 rows for HPE.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ONDS (company_id=518) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ONDS'), ('high', 'ONDS'), ('low', 'ONDS'), ('close', 'ONDS'), ('adj_close', 'ONDS'), ('volume', 'ONDS')]
✔ Inserted 1251 rows for ONDS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for SVMB (company_id=519) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'SVMB'), ('high', 'SVMB'), ('low', 'SVMB'), ('close', 'SVMB'), ('adj_close', 'SVMB'), ('volume', 'SVMB')]
✔ Inserted 910 rows for SVMB.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TOST (company_id=520) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TOST'), ('high', 'TOST'), ('low', 'TOST'), ('close', 'TOST'), ('adj_close', 'TOST'), ('volume', 'TOST')]
✔ Inserted 1051 rows for TOST.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TEAM (company_id=521) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TEAM'), ('high', 'TEAM'), ('low', 'TEAM'), ('close', 'TEAM'), ('adj_close', 'TEAM'), ('volume', 'TEAM')]
✔ Inserted 2507 rows for TEAM.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for BRQSF (company_id=522) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'BRQSF'), ('high', 'BRQSF'), ('low', 'BRQSF'), ('close', 'BRQSF'), ('adj_close', 'BRQSF'), ('volume', 'BRQSF')]
✔ Inserted 2514 rows for BRQSF.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for COUR (company_id=523) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'COUR'), ('high', 'COUR'), ('low', 'COUR'), ('close', 'COUR'), ('adj_close', 'COUR'), ('volume', 'COUR')]
✔ Inserted 1172 rows for COUR.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ASFT (company_id=524) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ASFT'), ('high', 'ASFT'), ('low', 'ASFT'), ('close', 'ASFT'), ('adj_close', 'ASFT'), ('volume', 'ASFT')]
✔ Inserted 1959 rows for ASFT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for GOOGL (company_id=525) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'GOOGL'), ('high', 'GOOGL'), ('low', 'GOOGL'), ('close', 'GOOGL'), ('adj_close', 'GOOGL'), ('volume', 'GOOGL')]
✔ Inserted 2514 rows for GOOGL.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ICHR (company_id=526) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ICHR'), ('high', 'ICHR'), ('low', 'ICHR'), ('close', 'ICHR'), ('adj_close', 'ICHR'), ('volume', 'ICHR')]
✔ Inserted 2254 rows for ICHR.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for GTLB (company_id=527) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'GTLB'), ('high', 'GTLB'), ('low', 'GTLB'), ('close', 'GTLB'), ('adj_close', 'GTLB'), ('volume', 'GTLB')]
✔ Inserted 1035 rows for GTLB.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for EHVVF (company_id=528) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'EHVVF'), ('high', 'EHVVF'), ('low', 'EHVVF'), ('close', 'EHVVF'), ('adj_close', 'EHVVF'), ('volume', 'EHVVF')]
✔ Inserted 2247 rows for EHVVF.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for DAVA (company_id=529) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'DAVA'), ('high', 'DAVA'), ('low', 'DAVA'), ('close', 'DAVA'), ('adj_close', 'DAVA'), ('volume', 'DAVA')]
✔ Inserted 1845 rows for DAVA.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for OKTA (company_id=530) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'OKTA'), ('high', 'OKTA'), ('low', 'OKTA'), ('close', 'OKTA'), ('adj_close', 'OKTA'), ('volume', 'OKTA')]
✔ Inserted 2173 rows for OKTA.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TENB (company_id=531) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TENB'), ('high', 'TENB'), ('low', 'TENB'), ('close', 'TENB'), ('adj_close', 'TENB'), ('volume', 'TENB')]
✔ Inserted 1846 rows for TENB.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for KULR (company_id=532) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'KULR'), ('high', 'KULR'), ('low', 'KULR'), ('close', 'KULR'), ('adj_close', 'KULR'), ('volume', 'KULR')]
✔ Inserted 1851 rows for KULR.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for BE (company_id=533) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'BE'), ('high', 'BE'), ('low', 'BE'), ('close', 'BE'), ('adj_close', 'BE'), ('volume', 'BE')]
✔ Inserted 1847 rows for BE.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for PHUN (company_id=534) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'PHUN'), ('high', 'PHUN'), ('low', 'PHUN'), ('close', 'PHUN'), ('adj_close', 'PHUN'), ('volume', 'PHUN')]
✔ Inserted 2283 rows for PHUN.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CDLX (company_id=535) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CDLX'), ('high', 'CDLX'), ('low', 'CDLX'), ('close', 'CDLX'), ('adj_close', 'CDLX'), ('volume', 'CDLX')]
✔ Inserted 1961 rows for CDLX.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for BL (company_id=536) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'BL'), ('high', 'BL'), ('low', 'BL'), ('close', 'BL'), ('adj_close', 'BL'), ('volume', 'BL')]
✔ Inserted 2283 rows for BL.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for AIP (company_id=537) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'AIP'), ('high', 'AIP'), ('low', 'AIP'), ('close', 'AIP'), ('adj_close', 'AIP'), ('volume', 'AIP')]
✔ Inserted 1026 rows for AIP.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ZDGE (company_id=538) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ZDGE'), ('high', 'ZDGE'), ('low', 'ZDGE'), ('close', 'ZDGE'), ('adj_close', 'ZDGE'), ('volume', 'ZDGE')]
✔ Inserted 2386 rows for ZDGE.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TTD (company_id=539) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TTD'), ('high', 'TTD'), ('low', 'TTD'), ('close', 'TTD'), ('adj_close', 'TTD'), ('volume', 'TTD')]
✔ Inserted 2310 rows for TTD.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for SEGG (company_id=540) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'SEGG'), ('high', 'SEGG'), ('low', 'SEGG'), ('close', 'SEGG'), ('adj_close', 'SEGG'), ('volume', 'SEGG')]
✔ Inserted 616 rows for SEGG.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for HNGE (company_id=541) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'HNGE'), ('high', 'HNGE'), ('low', 'HNGE'), ('close', 'HNGE'), ('adj_close', 'HNGE'), ('volume', 'HNGE')]
✔ Inserted 131 rows for HNGE.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for VRT (company_id=542) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'VRT'), ('high', 'VRT'), ('low', 'VRT'), ('close', 'VRT'), ('adj_close', 'VRT'), ('volume', 'VRT')]
✔ Inserted 1841 rows for VRT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for WORX (company_id=543) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'WORX'), ('high', 'WORX'), ('low', 'WORX'), ('close', 'WORX'), ('adj_close', 'WORX'), ('volume', 'WORX')]
✔ Inserted 2299 rows for WORX.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for YYAI (company_id=544) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'YYAI'), ('high', 'YYAI'), ('low', 'YYAI'), ('close', 'YYAI'), ('adj_close', 'YYAI'), ('volume', 'YYAI')]
✔ Inserted 1228 rows for YYAI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for BRZE (company_id=545) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'BRZE'), ('high', 'BRZE'), ('low', 'BRZE'), ('close', 'BRZE'), ('adj_close', 'BRZE'), ('volume', 'BRZE')]
✔ Inserted 1011 rows for BRZE.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for UPYY (company_id=546) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'UPYY'), ('high', 'UPYY'), ('low', 'UPYY'), ('close', 'UPYY'), ('adj_close', 'UPYY'), ('volume', 'UPYY')]
✔ Inserted 923 rows for UPYY.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CAHO (company_id=547) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CAHO'), ('high', 'CAHO'), ('low', 'CAHO'), ('close', 'CAHO'), ('adj_close', 'CAHO'), ('volume', 'CAHO')]
✔ Inserted 1004 rows for CAHO.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for VREX (company_id=548) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'VREX'), ('high', 'VREX'), ('low', 'VREX'), ('close', 'VREX'), ('adj_close', 'VREX'), ('volume', 'VREX')]
✔ Inserted 2226 rows for VREX.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CARS (company_id=549) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CARS'), ('high', 'CARS'), ('low', 'CARS'), ('close', 'CARS'), ('adj_close', 'CARS'), ('volume', 'CARS')]
✔ Inserted 2136 rows for CARS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TRVG (company_id=550) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TRVG'), ('high', 'TRVG'), ('low', 'TRVG'), ('close', 'TRVG'), ('adj_close', 'TRVG'), ('volume', 'TRVG')]
✔ Inserted 2249 rows for TRVG.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CRCW (company_id=551) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CRCW'), ('high', 'CRCW'), ('low', 'CRCW'), ('close', 'CRCW'), ('adj_close', 'CRCW'), ('volume', 'CRCW')]
✔ Inserted 2054 rows for CRCW.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for DXC (company_id=552) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'DXC'), ('high', 'DXC'), ('low', 'DXC'), ('close', 'DXC'), ('adj_close', 'DXC'), ('volume', 'DXC')]
✔ Inserted 2514 rows for DXC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for FRSX (company_id=553) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'FRSX'), ('high', 'FRSX'), ('low', 'FRSX'), ('close', 'FRSX'), ('adj_close', 'FRSX'), ('volume', 'FRSX')]
✔ Inserted 2126 rows for FRSX.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for REKR (company_id=554) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'REKR'), ('high', 'REKR'), ('low', 'REKR'), ('close', 'REKR'), ('adj_close', 'REKR'), ('volume', 'REKR')]
✔ Inserted 2074 rows for REKR.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CFLT (company_id=555) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CFLT'), ('high', 'CFLT'), ('low', 'CFLT'), ('close', 'CFLT'), ('adj_close', 'CFLT'), ('volume', 'CFLT')]
✔ Inserted 1113 rows for CFLT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for VS (company_id=556) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'VS'), ('high', 'VS'), ('low', 'VS'), ('close', 'VS'), ('adj_close', 'VS'), ('volume', 'VS')]
✔ Inserted 2514 rows for VS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for AGMH (company_id=557) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'AGMH'), ('high', 'AGMH'), ('low', 'AGMH'), ('close', 'AGMH'), ('adj_close', 'AGMH'), ('volume', 'AGMH')]
✔ Inserted 1915 rows for AGMH.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ESTC (company_id=558) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ESTC'), ('high', 'ESTC'), ('low', 'ESTC'), ('close', 'ESTC'), ('adj_close', 'ESTC'), ('volume', 'ESTC')]
✔ Inserted 1796 rows for ESTC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for RBBN (company_id=559) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'RBBN'), ('high', 'RBBN'), ('low', 'RBBN'), ('close', 'RBBN'), ('adj_close', 'RBBN'), ('volume', 'RBBN')]
✔ Inserted 2514 rows for RBBN.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for MYND (company_id=560) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'MYND'), ('high', 'MYND'), ('low', 'MYND'), ('close', 'MYND'), ('adj_close', 'MYND'), ('volume', 'MYND')]
✔ Inserted 2054 rows for MYND.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for GFS (company_id=561) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'GFS'), ('high', 'GFS'), ('low', 'GFS'), ('close', 'GFS'), ('adj_close', 'GFS'), ('volume', 'GFS')]
✔ Inserted 1025 rows for GFS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CSAI (company_id=562) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CSAI'), ('high', 'CSAI'), ('low', 'CSAI'), ('close', 'CSAI'), ('adj_close', 'CSAI'), ('volume', 'CSAI')]
✔ Inserted 209 rows for CSAI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for PNXP (company_id=563) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'PNXP'), ('high', 'PNXP'), ('low', 'PNXP'), ('close', 'PNXP'), ('adj_close', 'PNXP'), ('volume', 'PNXP')]
✔ Inserted 653 rows for PNXP.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for PAGS (company_id=564) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'PAGS'), ('high', 'PAGS'), ('low', 'PAGS'), ('close', 'PAGS'), ('adj_close', 'PAGS'), ('volume', 'PAGS')]
✔ Inserted 1973 rows for PAGS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for RDDT (company_id=565) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'RDDT'), ('high', 'RDDT'), ('low', 'RDDT'), ('close', 'RDDT'), ('adj_close', 'RDDT'), ('volume', 'RDDT')]
✔ Inserted 424 rows for RDDT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ZS (company_id=566) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ZS'), ('high', 'ZS'), ('low', 'ZS'), ('close', 'ZS'), ('adj_close', 'ZS'), ('volume', 'ZS')]
✔ Inserted 1937 rows for ZS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for AIJTY (company_id=567) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'AIJTY'), ('high', 'AIJTY'), ('low', 'AIJTY'), ('close', 'AIJTY'), ('adj_close', 'AIJTY'), ('volume', 'AIJTY')]
✔ Inserted 2018 rows for AIJTY.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for LCHD (company_id=568) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'LCHD'), ('high', 'LCHD'), ('low', 'LCHD'), ('close', 'LCHD'), ('adj_close', 'LCHD'), ('volume', 'LCHD')]
✔ Inserted 1549 rows for LCHD.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for PT (company_id=569) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'PT'), ('high', 'PT'), ('low', 'PT'), ('close', 'PT'), ('adj_close', 'PT'), ('volume', 'PT')]
✔ Inserted 1782 rows for PT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TEM (company_id=570) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TEM'), ('high', 'TEM'), ('low', 'TEM'), ('close', 'TEM'), ('adj_close', 'TEM'), ('volume', 'TEM')]
✔ Inserted 365 rows for TEM.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for IDAI (company_id=571) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'IDAI'), ('high', 'IDAI'), ('low', 'IDAI'), ('close', 'IDAI'), ('adj_close', 'IDAI'), ('volume', 'IDAI')]
✔ Inserted 1197 rows for IDAI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for RDVT (company_id=572) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'RDVT'), ('high', 'RDVT'), ('low', 'RDVT'), ('close', 'RDVT'), ('adj_close', 'RDVT'), ('volume', 'RDVT')]
✔ Inserted 1930 rows for RDVT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for IBEX (company_id=573) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'IBEX'), ('high', 'IBEX'), ('low', 'IBEX'), ('close', 'IBEX'), ('adj_close', 'IBEX'), ('volume', 'IBEX')]
✔ Inserted 1334 rows for IBEX.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ZEPP (company_id=574) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ZEPP'), ('high', 'ZEPP'), ('low', 'ZEPP'), ('close', 'ZEPP'), ('adj_close', 'ZEPP'), ('volume', 'ZEPP')]
✔ Inserted 1962 rows for ZEPP.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for JAMF (company_id=575) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'JAMF'), ('high', 'JAMF'), ('low', 'JAMF'), ('close', 'JAMF'), ('adj_close', 'JAMF'), ('volume', 'JAMF')]
✔ Inserted 1346 rows for JAMF.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for FDCT (company_id=576) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'FDCT'), ('high', 'FDCT'), ('low', 'FDCT'), ('close', 'FDCT'), ('adj_close', 'FDCT'), ('volume', 'FDCT')]
✔ Inserted 1377 rows for FDCT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for BILI (company_id=577) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'BILI'), ('high', 'BILI'), ('low', 'BILI'), ('close', 'BILI'), ('adj_close', 'BILI'), ('volume', 'BILI')]
✔ Inserted 1929 rows for BILI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CLPS (company_id=578) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CLPS'), ('high', 'CLPS'), ('low', 'CLPS'), ('close', 'CLPS'), ('adj_close', 'CLPS'), ('volume', 'CLPS')]
✔ Inserted 1888 rows for CLPS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for DAY (company_id=579) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'DAY'), ('high', 'DAY'), ('low', 'DAY'), ('close', 'DAY'), ('adj_close', 'DAY'), ('volume', 'DAY')]
✔ Inserted 1909 rows for DAY.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CANG (company_id=580) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CANG'), ('high', 'CANG'), ('low', 'CANG'), ('close', 'CANG'), ('adj_close', 'CANG'), ('volume', 'CANG')]
✔ Inserted 1846 rows for CANG.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ALAR (company_id=581) ...

1 Failed download:
['NTCS']: YFTzMissingError('possibly delisted; no timezone found')

⚠️ NTCS: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for AIXI (company_id=833) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'AIXI'), ('high', 'AIXI'), ('low', 'AIXI'), ('close', 'AIXI'), ('adj_close', 'AIXI'), ('volume', 'AIXI')]
✔ Inserted 684 rows for AIXI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for PODC (company_id=834) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'PODC'), ('high', 'PODC'), ('low', 'PODC'), ('close', 'PODC'), ('adj_close', 'PODC'), ('volume', 'PODC')]
✔ Inserted 558 rows for PODC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for MFI (company_id=835) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'MFI'), ('high', 'MFI'), ('low', 'MFI'), ('close', 'MFI'), ('adj_close', 'MFI'), ('volume', 'MFI')]
✔ Inserted 403 rows for MFI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TANAF (company_id=836) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TANAF'), ('high', 'TANAF'), ('low', 'TANAF'), ('close', 'TANAF'), ('adj_close', 'TANAF'), ('volume', 'TANAF')]
✔ Inserted 374 rows for TANAF.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for SVCO (company_id=837) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'SVCO'), ('high', 'SVCO'), ('low', 'SVCO'), ('close', 'SVCO'), ('adj_close', 'SVCO'), ('volume', 'SVCO')]
✔ Inserted 390 rows for SVCO.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for RBRK (company_id=838) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'RBRK'), ('high', 'RBRK'), ('low', 'RBRK'), ('close', 'RBRK'), ('adj_close', 'RBRK'), ('volume', 'RBRK')]
✔ Inserted 400 rows for RBRK.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ELWS (company_id=839) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ELWS'), ('high', 'ELWS'), ('low', 'ELWS'), ('close', 'ELWS'), ('adj_close', 'ELWS'), ('volume', 'ELWS')]
✔ Inserted 590 rows for ELWS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TKMO (company_id=840) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TKMO'), ('high', 'TKMO'), ('low', 'TKMO'), ('close', 'TKMO'), ('adj_close', 'TKMO'), ('volume', 'TKMO')]
✔ Inserted 451 rows for TKMO.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for LAES (company_id=841) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'LAES'), ('high', 'LAES'), ('low', 'LAES'), ('close', 'LAES'), ('adj_close', 'LAES'), ('volume', 'LAES')]
✔ Inserted 632 rows for LAES.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for LGCL (company_id=842) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'LGCL'), ('high', 'LGCL'), ('low', 'LGCL'), ('close', 'LGCL'), ('adj_close', 'LGCL'), ('volume', 'LGCL')]
✔ Inserted 436 rows for LGCL.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for UMAC (company_id=843) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'UMAC'), ('high', 'UMAC'), ('low', 'UMAC'), ('close', 'UMAC'), ('adj_close', 'UMAC'), ('volume', 'UMAC')]
✔ Inserted 449 rows for UMAC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for YAAS (company_id=844) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'YAAS'), ('high', 'YAAS'), ('low', 'YAAS'), ('close', 'YAAS'), ('adj_close', 'YAAS'), ('volume', 'YAAS')]
✔ Inserted 234 rows for YAAS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for NVNI (company_id=845) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'NVNI'), ('high', 'NVNI'), ('low', 'NVNI'), ('close', 'NVNI'), ('adj_close', 'NVNI'), ('volume', 'NVNI')]
✔ Inserted 983 rows for NVNI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for LZMH (company_id=846) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'LZMH'), ('high', 'LZMH'), ('low', 'LZMH'), ('close', 'LZMH'), ('adj_close', 'LZMH'), ('volume', 'LZMH')]
✔ Inserted 190 rows for LZMH.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ATGL (company_id=847) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ATGL'), ('high', 'ATGL'), ('low', 'ATGL'), ('close', 'ATGL'), ('adj_close', 'ATGL'), ('volume', 'ATGL')]
✔ Inserted 521 rows for ATGL.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for PONY (company_id=848) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'PONY'), ('high', 'PONY'), ('low', 'PONY'), ('close', 'PONY'), ('adj_close', 'PONY'), ('volume', 'PONY')]
✔ Inserted 250 rows for PONY.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for LGCB (company_id=849) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'LGCB'), ('high', 'LGCB'), ('low', 'LGCB'), ('close', 'LGCB'), ('adj_close', 'LGCB'), ('volume', 'LGCB')]
✔ Inserted 487 rows for LGCB.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for RMXI (company_id=850) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'RMXI'), ('high', 'RMXI'), ('low', 'RMXI'), ('close', 'RMXI'), ('adj_close', 'RMXI'), ('volume', 'RMXI')]
✔ Inserted 171 rows for RMXI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ABXXF (company_id=851) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ABXXF'), ('high', 'ABXXF'), ('low', 'ABXXF'), ('close', 'ABXXF'), ('adj_close', 'ABXXF'), ('volume', 'ABXXF')]
✔ Inserted 1241 rows for ABXXF.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for LNKS (company_id=852) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'LNKS'), ('high', 'LNKS'), ('low', 'LNKS'), ('close', 'LNKS'), ('adj_close', 'LNKS'), ('volume', 'LNKS')]
✔ Inserted 245 rows for LNKS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ARM (company_id=853) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ARM'), ('high', 'ARM'), ('low', 'ARM'), ('close', 'ARM'), ('adj_close', 'ARM'), ('volume', 'ARM')]
✔ Inserted 554 rows for ARM.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for NATL (company_id=854) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'NATL'), ('high', 'NATL'), ('low', 'NATL'), ('close', 'NATL'), ('adj_close', 'NATL'), ('volume', 'NATL')]
✔ Inserted 535 rows for NATL.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for NXNT (company_id=855) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'NXNT'), ('high', 'NXNT'), ('low', 'NXNT'), ('close', 'NXNT'), ('adj_close', 'NXNT'), ('volume', 'NXNT')]
✔ Inserted 43 rows for NXNT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for MNDR (company_id=856) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'MNDR'), ('high', 'MNDR'), ('low', 'MNDR'), ('close', 'MNDR'), ('adj_close', 'MNDR'), ('volume', 'MNDR')]
✔ Inserted 411 rows for MNDR.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for YQAI (company_id=857) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'YQAI'), ('high', 'YQAI'), ('low', 'YQAI'), ('close', 'YQAI'), ('adj_close', 'YQAI'), ('volume', 'YQAI')]

1 Failed download:
['ALXY']: YFPricesMissingError('possibly delisted; no price data found  (1d 2015-11-28 -> 2025-11-28)')

✔ Inserted 2514 rows for YQAI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ALXY (company_id=858) ...
⚠️ ALXY: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ORKT (company_id=859) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ORKT'), ('high', 'ORKT'), ('low', 'ORKT'), ('close', 'ORKT'), ('adj_close', 'ORKT'), ('volume', 'ORKT')]
✔ Inserted 338 rows for ORKT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for IMAA (company_id=860) ...

1 Failed download:
['IMAA']: YFPricesMissingError('possibly delisted; no price data found  (1d 2015-11-28 -> 2025-11-28)')

⚠️ IMAA: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for LDTCF (company_id=861) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'LDTCF'), ('high', 'LDTCF'), ('low', 'LDTCF'), ('close', 'LDTCF'), ('adj_close', 'LDTCF'), ('volume', 'LDTCF')]
✔ Inserted 1194 rows for LDTCF.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for SBET (company_id=862) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'SBET'), ('high', 'SBET'), ('low', 'SBET'), ('close', 'SBET'), ('adj_close', 'SBET'), ('volume', 'SBET')]
✔ Inserted 2514 rows for SBET.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for BLIV (company_id=863) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'BLIV'), ('high', 'BLIV'), ('low', 'BLIV'), ('close', 'BLIV'), ('adj_close', 'BLIV'), ('volume', 'BLIV')]
✔ Inserted 164 rows for BLIV.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for KNRX (company_id=864) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'KNRX'), ('high', 'KNRX'), ('low', 'KNRX'), ('close', 'KNRX'), ('adj_close', 'KNRX'), ('volume', 'KNRX')]
✔ Inserted 43 rows for KNRX.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for RMSG (company_id=865) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'RMSG'), ('high', 'RMSG'), ('low', 'RMSG'), ('close', 'RMSG'), ('adj_close', 'RMSG'), ('volume', 'RMSG')]
✔ Inserted 1044 rows for RMSG.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for GOAI (company_id=866) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'GOAI'), ('high', 'GOAI'), ('low', 'GOAI'), ('close', 'GOAI'), ('adj_close', 'GOAI'), ('volume', 'GOAI')]

1 Failed download:
['LDXC']: YFPricesMissingError('possibly delisted; no price data found  (1d 2015-11-28 -> 2025-11-28)')

✔ Inserted 2514 rows for GOAI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for LDXC (company_id=867) ...
⚠️ LDXC: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for GAFC (company_id=868) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'GAFC'), ('high', 'GAFC'), ('low', 'GAFC'), ('close', 'GAFC'), ('adj_close', 'GAFC'), ('volume', 'GAFC')]
✔ Inserted 2 rows for GAFC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for WCT (company_id=869) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'WCT'), ('high', 'WCT'), ('low', 'WCT'), ('close', 'WCT'), ('adj_close', 'WCT'), ('volume', 'WCT')]
✔ Inserted 290 rows for WCT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for WAY (company_id=870) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'WAY'), ('high', 'WAY'), ('low', 'WAY'), ('close', 'WAY'), ('adj_close', 'WAY'), ('volume', 'WAY')]
✔ Inserted 370 rows for WAY.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for SELX (company_id=871) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'SELX'), ('high', 'SELX'), ('low', 'SELX'), ('close', 'SELX'), ('adj_close', 'SELX'), ('volume', 'SELX')]
✔ Inserted 859 rows for SELX.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for YMT (company_id=872) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'YMT'), ('high', 'YMT'), ('low', 'YMT'), ('close', 'YMT'), ('adj_close', 'YMT'), ('volume', 'YMT')]
✔ Inserted 71 rows for YMT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ZDAN (company_id=873) ...

1 Failed download:
['ZDAN']: YFTzMissingError('possibly delisted; no timezone found')

⚠️ ZDAN: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TE (company_id=874) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TE'), ('high', 'TE'), ('low', 'TE'), ('close', 'TE'), ('adj_close', 'TE'), ('volume', 'TE')]
✔ Inserted 1479 rows for TE.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for MASK (company_id=875) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'MASK'), ('high', 'MASK'), ('low', 'MASK'), ('close', 'MASK'), ('adj_close', 'MASK'), ('volume', 'MASK')]
✔ Inserted 223 rows for MASK.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for FATN (company_id=876) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'FATN'), ('high', 'FATN'), ('low', 'FATN'), ('close', 'FATN'), ('adj_close', 'FATN'), ('volume', 'FATN')]
✔ Inserted 162 rows for FATN.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for SNT (company_id=877) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'SNT'), ('high', 'SNT'), ('low', 'SNT'), ('close', 'SNT'), ('adj_close', 'SNT'), ('volume', 'SNT')]
✔ Inserted 2514 rows for SNT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for HNIT (company_id=878) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'HNIT'), ('high', 'HNIT'), ('low', 'HNIT'), ('close', 'HNIT'), ('adj_close', 'HNIT'), ('volume', 'HNIT')]
✔ Inserted 3 rows for HNIT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ZENA (company_id=879) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ZENA'), ('high', 'ZENA'), ('low', 'ZENA'), ('close', 'ZENA'), ('adj_close', 'ZENA'), ('volume', 'ZENA')]

1 Failed download:
['PRGY']: YFPricesMissingError('possibly delisted; no price data found  (1d 2015-11-28 -> 2025-11-28)')

✔ Inserted 291 rows for ZENA.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for PRGY (company_id=880) ...
⚠️ PRGY: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for GMHS (company_id=881) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'GMHS'), ('high', 'GMHS'), ('low', 'GMHS'), ('close', 'GMHS'), ('adj_close', 'GMHS'), ('volume', 'GMHS')]
✔ Inserted 608 rows for GMHS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for GMTH (company_id=882) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'GMTH'), ('high', 'GMTH'), ('low', 'GMTH'), ('close', 'GMTH'), ('adj_close', 'GMTH'), ('volume', 'GMTH')]
✔ Inserted 322 rows for GMTH.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for HPAI (company_id=883) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'HPAI'), ('high', 'HPAI'), ('low', 'HPAI'), ('close', 'HPAI'), ('adj_close', 'HPAI'), ('volume', 'HPAI')]
✔ Inserted 331 rows for HPAI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for GCL (company_id=884) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'GCL'), ('high', 'GCL'), ('low', 'GCL'), ('close', 'GCL'), ('adj_close', 'GCL'), ('volume', 'GCL')]
✔ Inserted 906 rows for GCL.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for LHSW (company_id=885) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'LHSW'), ('high', 'LHSW'), ('low', 'LHSW'), ('close', 'LHSW'), ('adj_close', 'LHSW'), ('volume', 'LHSW')]
✔ Inserted 165 rows for LHSW.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CCIX (company_id=886) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CCIX'), ('high', 'CCIX'), ('low', 'CCIX'), ('close', 'CCIX'), ('adj_close', 'CCIX'), ('volume', 'CCIX')]
✔ Inserted 361 rows for CCIX.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for LAWR (company_id=887) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'LAWR'), ('high', 'LAWR'), ('low', 'LAWR'), ('close', 'LAWR'), ('adj_close', 'LAWR'), ('volume', 'LAWR')]
✔ Inserted 94 rows for LAWR.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CCCX (company_id=888) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CCCX'), ('high', 'CCCX'), ('low', 'CCCX'), ('close', 'CCCX'), ('adj_close', 'CCCX'), ('volume', 'CCCX')]
✔ Inserted 102 rows for CCCX.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for DGNX (company_id=889) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'DGNX'), ('high', 'DGNX'), ('low', 'DGNX'), ('close', 'DGNX'), ('adj_close', 'DGNX'), ('volume', 'DGNX')]
✔ Inserted 215 rows for DGNX.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for FVN (company_id=890) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'FVN'), ('high', 'FVN'), ('low', 'FVN'), ('close', 'FVN'), ('adj_close', 'FVN'), ('volume', 'FVN')]
✔ Inserted 267 rows for FVN.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for FOXX (company_id=891) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'FOXX'), ('high', 'FOXX'), ('low', 'FOXX'), ('close', 'FOXX'), ('adj_close', 'FOXX'), ('volume', 'FOXX')]
✔ Inserted 831 rows for FOXX.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for GVSE (company_id=892) ...

1 Failed download:
['GVSE']: YFTzMissingError('possibly delisted; no timezone found')

⚠️ GVSE: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for SNDK (company_id=893) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'SNDK'), ('high', 'SNDK'), ('low', 'SNDK'), ('close', 'SNDK'), ('adj_close', 'SNDK'), ('volume', 'SNDK')]
✔ Inserted 199 rows for SNDK.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TGHL (company_id=894) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TGHL'), ('high', 'TGHL'), ('low', 'TGHL'), ('close', 'TGHL'), ('adj_close', 'TGHL'), ('volume', 'TGHL')]
✔ Inserted 64 rows for TGHL.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for OWLS (company_id=895) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'OWLS'), ('high', 'OWLS'), ('low', 'OWLS'), ('close', 'OWLS'), ('adj_close', 'OWLS'), ('volume', 'OWLS')]
✔ Inserted 30 rows for OWLS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ATHR (company_id=896) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'ATHR'), ('high', 'ATHR'), ('low', 'ATHR'), ('close', 'ATHR'), ('adj_close', 'ATHR'), ('volume', 'ATHR')]
✔ Inserted 160 rows for ATHR.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for BACQ (company_id=897) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'BACQ'), ('high', 'BACQ'), ('low', 'BACQ'), ('close', 'BACQ'), ('adj_close', 'BACQ'), ('volume', 'BACQ')]
✔ Inserted 248 rows for BACQ.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for SAGT (company_id=898) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'SAGT'), ('high', 'SAGT'), ('low', 'SAGT'), ('close', 'SAGT'), ('adj_close', 'SAGT'), ('volume', 'SAGT')]
✔ Inserted 184 rows for SAGT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for SAIL (company_id=899) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'SAIL'), ('high', 'SAIL'), ('low', 'SAIL'), ('close', 'SAIL'), ('adj_close', 'SAIL'), ('volume', 'SAIL')]
✔ Inserted 199 rows for SAIL.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for MGRT (company_id=900) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'MGRT'), ('high', 'MGRT'), ('low', 'MGRT'), ('close', 'MGRT'), ('adj_close', 'MGRT'), ('volume', 'MGRT')]
✔ Inserted 95 rows for MGRT.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for FUSE (company_id=901) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'FUSE'), ('high', 'FUSE'), ('low', 'FUSE'), ('close', 'FUSE'), ('adj_close', 'FUSE'), ('volume', 'FUSE')]
✔ Inserted 937 rows for FUSE.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for DAIC (company_id=902) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'DAIC'), ('high', 'DAIC'), ('low', 'DAIC'), ('close', 'DAIC'), ('adj_close', 'DAIC'), ('volume', 'DAIC')]
✔ Inserted 111 rows for DAIC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for BTTC (company_id=903) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'BTTC'), ('high', 'BTTC'), ('low', 'BTTC'), ('close', 'BTTC'), ('adj_close', 'BTTC'), ('volume', 'BTTC')]
✔ Inserted 40 rows for BTTC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for GIBO (company_id=904) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'GIBO'), ('high', 'GIBO'), ('low', 'GIBO'), ('close', 'GIBO'), ('adj_close', 'GIBO'), ('volume', 'GIBO')]
✔ Inserted 571 rows for GIBO.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for VWAV (company_id=905) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'VWAV'), ('high', 'VWAV'), ('low', 'VWAV'), ('close', 'VWAV'), ('adj_close', 'VWAV'), ('volume', 'VWAV')]
✔ Inserted 96 rows for VWAV.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CHOW (company_id=906) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CHOW'), ('high', 'CHOW'), ('low', 'CHOW'), ('close', 'CHOW'), ('adj_close', 'CHOW'), ('volume', 'CHOW')]
✔ Inserted 52 rows for CHOW.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for CTW (company_id=907) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'CTW'), ('high', 'CTW'), ('low', 'CTW'), ('close', 'CTW'), ('adj_close', 'CTW'), ('volume', 'CTW')]
✔ Inserted 80 rows for CTW.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for TCGL (company_id=908) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'TCGL'), ('high', 'TCGL'), ('low', 'TCGL'), ('close', 'TCGL'), ('adj_close', 'TCGL'), ('volume', 'TCGL')]

1 Failed download:
['BAO']: YFPricesMissingError('possibly delisted; no price data found  (1d 2015-11-28 -> 2025-11-28)')

✔ Inserted 31 rows for TCGL.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for BAO (company_id=909) ...
⚠️ BAO: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for SUWA (company_id=910) ...

1 Failed download:
['SUWA']: YFTzMissingError('possibly delisted; no timezone found')

⚠️ SUWA: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for PLTS (company_id=911) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'PLTS'), ('high', 'PLTS'), ('low', 'PLTS'), ('close', 'PLTS'), ('adj_close', 'PLTS'), ('volume', 'PLTS')]
✔ Inserted 49 rows for PLTS.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for NIQ (company_id=912) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'NIQ'), ('high', 'NIQ'), ('low', 'NIQ'), ('close', 'NIQ'), ('adj_close', 'NIQ'), ('volume', 'NIQ')]
✔ Inserted 90 rows for NIQ.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for DBIM (company_id=913) ...

1 Failed download:
['DBIM']: YFTzMissingError('possibly delisted; no timezone found')

1 Failed download:
['ECST']: YFPricesMissingError('possibly delisted; no price data found  (1d 2015-11-28 -> 2025-11-28)')

⚠️ DBIM: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ECST (company_id=914) ...
⚠️ ECST: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for DKI (company_id=915) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'DKI'), ('high', 'DKI'), ('low', 'DKI'), ('close', 'DKI'), ('adj_close', 'DKI'), ('volume', 'DKI')]
✔ Inserted 78 rows for DKI.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for Q (company_id=916) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'Q'), ('high', 'Q'), ('low', 'Q'), ('close', 'Q'), ('adj_close', 'Q'), ('volume', 'Q')]
✔ Inserted 23 rows for Q.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for NTSK (company_id=917) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'NTSK'), ('high', 'NTSK'), ('low', 'NTSK'), ('close', 'NTSK'), ('adj_close', 'NTSK'), ('volume', 'NTSK')]
✔ Inserted 50 rows for NTSK.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for LOGC (company_id=918) ...
  Columns from yfinance: [('trade_date', ''), ('open', 'LOGC'), ('high', 'LOGC'), ('low', 'LOGC'), ('close', 'LOGC'), ('adj_close', 'LOGC'), ('volume', 'LOGC')]

1 Failed download:
['GBH']: YFPricesMissingError('possibly delisted; no price data found  (1d 2015-11-28 -> 2025-11-28)')

✔ Inserted 1243 rows for LOGC.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for GBH (company_id=919) ...
⚠️ GBH: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for GDNT (company_id=920) ...

1 Failed download:
['GDNT']: YFTzMissingError('possibly delisted; no timezone found')

1 Failed download:
['ALD']: YFPricesMissingError('possibly delisted; no price data found  (1d 2015-11-28 -> 2025-11-28)')

⚠️ GDNT: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ALD (company_id=921) ...
⚠️ ALD: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for GLOO (company_id=922) ...

1 Failed download:
['KLK']: YFPricesMissingError('possibly delisted; no price data found  (1d 2015-11-28 -> 2025-11-28)')

  Columns from yfinance: [('trade_date', ''), ('open', 'GLOO'), ('high', 'GLOO'), ('low', 'GLOO'), ('close', 'GLOO'), ('adj_close', 'GLOO'), ('volume', 'GLOO')]
✔ Inserted 7 rows for GLOO.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for KLK (company_id=923) ...
⚠️ KLK: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for EVON (company_id=924) ...

1 Failed download:
['EVON']: YFPricesMissingError('possibly delisted; no price data found  (1d 2015-11-28 -> 2025-11-28)')

1 Failed download:
['BRAI']: YFPricesMissingError('possibly delisted; no price data found  (1d 2015-11-28 -> 2025-11-28)')

⚠️ EVON: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for BRAI (company_id=925) ...
⚠️ BRAI: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for ZSSK (company_id=926) ...

1 Failed download:
['ZSSK']: YFTzMissingError('possibly delisted; no timezone found')

⚠️ ZSSK: no price data found.

⬇️ Fetching from 2015-11-28 to 2025-11-28 for XYJG (company_id=927) ...

1 Failed download:
['XYJG']: YFTzMissingError('possibly delisted; no timezone found')

⚠️ XYJG: no price data found.

In [4]:
cur.execute("""
    SELECT company_id, trade_date, open, close
    FROM daily_price
    ORDER BY trade_date DESC
    LIMIT 10;
""")
rows = cur.fetchall()

print("\nSample rows from daily_price:")
for r in rows:
    print(r)

Sample rows from daily_price:
(10, datetime.date(2025, 11, 26), Decimal('42.2400'), Decimal('42.5800'))
(15, datetime.date(2025, 11, 26), Decimal('24.1000'), Decimal('23.9800'))
(8, datetime.date(2025, 11, 26), Decimal('616.6700'), Decimal('615.3500'))
(9, datetime.date(2025, 11, 26), Decimal('3.1400'), Decimal('3.0300'))
(1, datetime.date(2025, 11, 26), Decimal('66.4200'), Decimal('63.9700'))
(3, datetime.date(2025, 11, 26), Decimal('63.6000'), Decimal('65.3400'))
(2, datetime.date(2025, 11, 26), Decimal('210.0500'), Decimal('214.2400'))
(6, datetime.date(2025, 11, 26), Decimal('8.0000'), Decimal('7.8600'))
(4, datetime.date(2025, 11, 26), Decimal('255.2200'), Decimal('257.9200'))
(18, datetime.date(2025, 11, 26), Decimal('12.9900'), Decimal('13.4000'))

Check the data download status

In [5]:
print("\n" + "="*50)
print("Data download status check:")
print("="*50)

cur.execute("""
    SELECT COUNT(DISTINCT company_id) 
    FROM daily_price;
""")
companies_with_data = cur.fetchone()[0]

cur.execute("SELECT COUNT(*) FROM company;")
total_companies = cur.fetchone()[0]

companies_without_data = total_companies - companies_with_data

print(f"Number of total comapnies: {total_companies}")
print(f"Number of companies with data: {companies_with_data}")
print(f"Number of companies without data: {companies_without_data}")
print(f"Data coverage rate: {companies_with_data/total_companies*100:.1f}%")

if companies_without_data > 0:
    print(f"\nThe list of companies without data:")
    cur.execute("""
        SELECT c.company_id, c.ticker, c.company_name
        FROM company c
        LEFT JOIN daily_price dp ON c.company_id = dp.company_id
        WHERE dp.company_id IS NULL
        ORDER BY c.ticker;
    """)
    
    no_data_companies = cur.fetchall()
    for company_id, ticker, name in no_data_companies[:10]:
        print(f"  {ticker}: {name}")
    
    if len(no_data_companies) > 10:
        print(f"  ... There are {len(no_data_companies)-10}  more companies")

print(f"\nData volume statistics:")
cur.execute("""
    SELECT 
        COUNT(DISTINCT company_id) as companies,
        MIN(cnt) as min_records,
        MAX(cnt) as max_records,
        AVG(cnt)::INT as avg_records
    FROM (
        SELECT company_id, COUNT(*) as cnt
        FROM daily_price 
        GROUP BY company_id
    ) t;
""")

stats = cur.fetchone()
print(f"The number of companies with data: {stats[0]}")
print(f"Minimum number of records: {stats[1]}")
print(f"Maximum number of records: {stats[2]}")  
print(f"Average number of records: {stats[3]}")

==================================================
Data download status check:
==================================================
Number of total comapnies: 927
Number of companies with data: 907
Number of companies without data: 20
Data coverage rate: 97.8%

The list of companies without data:
  ALD: Altech Digital Co., Ltd.
  ALXY: MADE IN USA INC.
  BAO: BAO Holding Ltd.
  BRAI: Braiin Ltd
  CAST: FreeCast, Inc.
  DBIM: Dbim Holdings Ltd
  ECST: ECST Holdings Ltd
  EVON: EvoNexus Group LTD
  GBH: Gigabit Inc.
  GDNT: Guident Corp.
  ... There are 10  more companies

Data volume statistics:
The number of companies with data: 907
Minimum number of records: 2
Maximum number of records: 2514
Average number of records: 1770

# Create sec_fillings table & insert data from SEC EDGAR

In [1]:
!pip install -U "psycopg[binary]" pymongo requests beautifulsoup4 pandas

Requirement already satisfied: pymongo in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (4.15.4)
Requirement already satisfied: requests in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (4.14.2)
Requirement already satisfied: pandas in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (2.3.3)
Requirement already satisfied: psycopg[binary] in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (3.2.13)
Requirement already satisfied: tzdata in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from psycopg[binary]) (2025.2)
Requirement already satisfied: psycopg-binary==3.2.13 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from psycopg[binary]) (3.2.13)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from pymongo) (2.8.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from requests) (2025.8.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\milan_chen\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import psycopg
from pymongo import MongoClient
import requests
from bs4 import BeautifulSoup
from datetime import date
import time

pg_conn = psycopg.connect(
    host=os.getenv("PGHOST", "localhost"),
    port=os.getenv("PGPORT", "5432"),
    dbname=os.getenv("PGDATABASE", "final"),
    user=os.getenv("PGUSER", "postgres"),
    password=os.getenv("PGPASSWORD")
)
pg_cur = pg_conn.cursor()
print("Connected to PostgreSQL 'final'")

Connected to PostgreSQL 'final'

In [3]:
pg_cur.execute("""
    SELECT company_id, cik, ticker, company_name
    FROM company
    ORDER BY company_id;
""")

rows = pg_cur.fetchall()
print("Total rows fetched:", len(rows))

companies = []
for row in rows:
    company_id, cik, ticker, company_name = row
    companies.append({
        "company_id": company_id,
        "cik": cik,
        "ticker": ticker,
        "company_name": company_name
    })

for c in companies[:5]:
    print(c)

Total rows fetched: 927
{'company_id': 1, 'cik': '0000002186', 'ticker': 'BKTI', 'company_name': 'BK Technologies Corp'}
{'company_id': 2, 'cik': '0000002488', 'ticker': 'AMD', 'company_name': 'ADVANCED MICRO DEVICES INC'}
{'company_id': 3, 'cik': '0000004127', 'ticker': 'SWKS', 'company_name': 'SKYWORKS SOLUTIONS, INC.'}
{'company_id': 4, 'cik': '0000006281', 'ticker': 'ADI', 'company_name': 'ANALOG DEVICES INC'}
{'company_id': 5, 'cik': '0000006951', 'ticker': 'AMAT', 'company_name': 'APPLIED MATERIALS INC /DE'}

In [2]:
client = MongoClient("mongodb://localhost:27017")
db = client["sec_project"]
sec_filings = db["sec_filings"]

print("Connected to MongoDB: DB='sec_project', collection='sec_filings'")

Connected to MongoDB: DB='sec_project', collection='sec_filings'

In [5]:
db.drop_collection("sec_filings")
sec_filings = db["sec_filings"]

sec_filings.create_index([("cik", 1), ("accession_number", 1)], unique=True)
sec_filings.create_index([("company_id", 1), ("filing_type", 1), ("filing_date", -1)])
sec_filings.create_index([("raw_text", "text")])

print("✅ Recreated collection 'sec_filings'")
print("Collection reset. Current count:", sec_filings.count_documents({}))

✅ Recreated collection 'sec_filings'
Collection reset. Current count: 0

In [6]:
SEC_API_HEADERS = {
    "User-Agent": "your_name your_email@example.com",
    "Accept-Encoding": "gzip, deflate",
    "Host": "data.sec.gov"
}

SEC_ARCHIVES_HEADERS = {
    "User-Agent": "your_name your_email@example.com",
    "Accept-Encoding": "gzip, deflate"
}

FIXED_START = date(2015, 11, 28)

def fetch_company_submissions(cik_10):
    url = f"https://data.sec.gov/submissions/CIK{cik_10}.json"
    resp = requests.get(url, headers=SEC_API_HEADERS)
    if resp.status_code != 200:
        print(f"❌ Failed submissions for {cik_10}, status={resp.status_code}")
        return None
    return resp.json()

def extract_filings_meta(sub_json, cik_10):
    if not sub_json:
        return []

    recent = sub_json["filings"]["recent"]
    forms = recent.get("form", [])
    dates = recent.get("filingDate", [])
    accs  = recent.get("accessionNumber", [])
    docs  = recent.get("primaryDocument", [])

    filings = []
    for form, d, acc, doc in zip(forms, dates, accs, docs):
        if form not in ("10-K", "10-Q","8-K"):
            continue
        try:
            y, m, da = map(int, d.split("-"))
            f_date = date(y, m, da)
        except:
            continue
        if f_date < FIXED_START:
            continue

        filings.append({
            "cik": cik_10,
            "filing_type": form,
            "filing_date": f_date,
            "accession_number": acc,
            "primary_doc": doc
        })

    return filings

In [7]:
def build_filing_paths(cik_10, accession_number, primary_doc):
    cik_no_zero = str(int(cik_10))
    acc_nodash = accession_number.replace("-", "")

    base_dir = f"https://www.sec.gov/Archives/edgar/data/{cik_no_zero}/{acc_nodash}/"
    index_url = base_dir + f"{accession_number}-index.htm"
    main_doc_url = base_dir + primary_doc  # e.g. bkti20250930_10q.htm

    return base_dir, index_url, main_doc_url

def download_html(url):
    resp = requests.get(url, headers=SEC_ARCHIVES_HEADERS)
    if resp.status_code != 200:
        print(f"  ❌ Failed: {url} status={resp.status_code}")
        return None
    return resp.text

def html_to_text(html):
    soup = BeautifulSoup(html, "html.parser")
    for s in soup(["script", "style"]):
        s.decompose()
    lines = [line.strip() for line in soup.get_text("\n").splitlines()]
    return "\n".join(l for l in lines if l)

In [8]:
def process_company_filings(company):
    company_id = company["company_id"]
    cik_10 = company["cik"].zfill(10)
    ticker = company["ticker"]
    name = company["company_name"]

    print(f"\n=== CIK={cik_10} ticker={ticker} ===")

    sub_json = fetch_company_submissions(cik_10)
    if sub_json is None:
        print("  ⚠️ No submissions JSON")
        return

    filings = extract_filings_meta(sub_json, cik_10)
    print(f"  Found {len(filings)} filings.")

    inserted = 0

    for meta in filings:
        base_dir, index_url, main_doc_url = build_filing_paths(
            cik_10,
            meta["accession_number"],
            meta["primary_doc"]
        )

        print(f"  -> {meta['filing_type']} {meta['filing_date']}")

        # Try main doc first
        html = download_html(main_doc_url)
        used_index = False

        if html is None:
            print("     ⚠️ main doc failed; trying index")
            html = download_html(index_url)
            if html is None:
                print("     ⛔ Skip filing")
                continue
            used_index = True

        text = html_to_text(html)

        doc = {
            "company_id": company_id,
            "cik": cik_10,
            "ticker": ticker,
            "company_name": name,

            "filing_type": meta["filing_type"],
            "filing_date": meta["filing_date"].isoformat(),
            "accession_number": meta["accession_number"],
            "primary_doc": meta["primary_doc"],

            "source_main": main_doc_url,
            "source_index": index_url,
            "used_index_page": used_index,

            "raw_text": text
        }

        try:
            sec_filings.insert_one(doc)
            inserted += 1
            print("     ✔ inserted")
        except Exception as e:
            print("     ⚠️ skipped:", e)

    print(f"  ✅ Done. Inserted {inserted}.")

In [9]:
print("Total companies:", len(companies))

for idx, company in enumerate(companies, start=1):
    print(f"\n=== [{idx}/{len(companies)}] {company['ticker']} ===")
    process_company_filings(company)
    time.sleep(0.5)  

print("\n🎉 All companies processed!")

Total companies: 927

=== [1/927] BKTI ===

=== CIK=0000002186 ticker=BKTI ===
  Found 183 filings.
  -> 10-Q 2025-11-06
     ✔ inserted
  -> 8-K 2025-11-06
     ✔ inserted
  -> 8-K 2025-10-30
     ✔ inserted
  -> 8-K 2025-10-06
     ✔ inserted
  -> 10-Q 2025-08-14
     ✔ inserted
  -> 8-K 2025-08-14
     ✔ inserted
  -> 8-K 2025-07-14
     ✔ inserted
  -> 8-K 2025-06-18
     ✔ inserted
  -> 8-K 2025-06-03
     ✔ inserted
  -> 8-K 2025-05-13
     ✔ inserted
  -> 10-Q 2025-05-13
     ✔ inserted
  -> 8-K 2025-03-27
     ✔ inserted
  -> 10-K 2025-03-27
     ✔ inserted
  -> 8-K 2024-11-14
     ✔ inserted
  -> 10-Q 2024-11-14
     ✔ inserted
  -> 8-K 2024-11-06
     ✔ inserted
  -> 8-K 2024-11-04
     ✔ inserted
  -> 8-K 2024-08-08
     ✔ inserted
  -> 10-Q 2024-08-08
     ✔ inserted
  -> 8-K 2024-06-20
     ✔ inserted
  -> 8-K 2024-05-13
     ✔ inserted
  -> 8-K 2024-05-09
     ✔ inserted
  -> 10-Q 2024-05-09
     ✔ inserted
  -> 8-K 2024-03-14
     ✔ inserted
  -> 10-K 2024-03-14
     ✔ inserted
  -> 8-K 2024-01-29
     ✔ inserted
  -> 8-K 2024-01-03
     ✔ inserted
  -> 8-K 2023-12-14
     ✔ inserted
  -> 8-K 2023-11-13
     ✔ inserted
  -> 8-K 2023-11-09
     ✔ inserted
  -> 10-Q 2023-11-09
     ✔ inserted
  -> 8-K 2023-11-08
     ✔ inserted
  -> 8-K 2023-10-13
     ✔ inserted
  -> 8-K 2023-09-19
     ✔ inserted
  -> 8-K 2023-09-07
     ✔ inserted
  -> 8-K 2023-08-10
     ✔ inserted
  -> 10-Q 2023-08-10
     ✔ inserted
  -> 8-K 2023-05-10
     ✔ inserted
  -> 8-K 2023-05-04
     ✔ inserted
  -> 10-Q 2023-05-04
     ✔ inserted
  -> 8-K 2023-03-28
     ✔ inserted
  -> 8-K 2023-03-17
     ✔ inserted
  -> 10-K 2023-03-16
     ✔ inserted
  -> 8-K 2023-03-16
     ✔ inserted
  -> 8-K 2023-01-31
     ✔ inserted
  -> 8-K 2023-01-04
     ✔ inserted
  -> 8-K 2022-11-30
     ✔ inserted
  -> 8-K 2022-11-09
     ✔ inserted
  -> 10-Q 2022-11-04
     ✔ inserted
  -> 8-K 2022-11-03
     ✔ inserted
  -> 8-K 2022-11-03
     ✔ inserted
  -> 8-K 2022-09-29
     ✔ inserted
  -> 8-K 2022-08-16
     ✔ inserted
  -> 8-K 2022-08-11
     ✔ inserted
  -> 10-Q 2022-08-11
     ✔ inserted
  -> 8-K 2022-07-07
     ✔ inserted
  -> 8-K 2022-06-30
     ✔ inserted
  -> 8-K 2022-06-06
     ✔ inserted
  -> 8-K 2022-05-13
     ✔ inserted
  -> 8-K 2022-05-12
     ✔ inserted
  -> 10-Q 2022-05-12
     ✔ inserted
  -> 8-K 2022-04-21
     ✔ inserted
  -> 8-K 2022-04-07
     ✔ inserted
  -> 8-K 2022-03-17
     ✔ inserted
  -> 8-K 2022-03-17
     ✔ inserted
  -> 10-K 2022-03-17
     ✔ inserted
  -> 8-K 2022-01-11
     ✔ inserted
  -> 8-K 2021-12-22
     ✔ inserted
  -> 8-K 2021-12-21
     ✔ inserted
  -> 8-K 2021-12-21
     ✔ inserted
  -> 8-K 2021-11-12
     ✔ inserted
  -> 10-Q 2021-11-12
     ✔ inserted
  -> 8-K 2021-09-29
     ✔ inserted
  -> 8-K 2021-09-23
     ✔ inserted
  -> 8-K 2021-08-13
     ✔ inserted
  -> 8-K 2021-08-12
     ✔ inserted
  -> 10-Q 2021-08-12
     ✔ inserted
  -> 8-K 2021-07-20
     ✔ inserted
  -> 8-K 2021-07-12
     ✔ inserted
  -> 8-K 2021-06-09
     ✔ inserted
  -> 8-K 2021-05-17
     ✔ inserted
  -> 8-K 2021-05-13
     ✔ inserted
  -> 10-Q 2021-05-13
     ✔ inserted
  -> 8-K 2021-03-17
     ✔ inserted
  -> 8-K 2021-03-05
     ✔ inserted
  -> 10-K 2021-03-03
     ✔ inserted
  -> 8-K 2021-03-03
     ✔ inserted
  -> 8-K 2020-12-11
     ✔ inserted
  -> 8-K 2020-11-13
     ✔ inserted
  -> 10-Q 2020-11-12
     ✔ inserted
  -> 8-K 2020-11-12
     ✔ inserted
  -> 8-K 2020-09-17
     ✔ inserted
  -> 8-K 2020-09-03
     ✔ inserted
  -> 8-K 2020-08-07
     ✔ inserted
  -> 10-Q 2020-08-05
     ✔ inserted
  -> 8-K 2020-08-05
     ✔ inserted
  -> 8-K 2020-07-23
     ✔ inserted
  -> 8-K 2020-06-24
     ✔ inserted
  -> 8-K 2020-06-10
     ✔ inserted
  -> 8-K 2020-05-15
     ✔ inserted
  -> 10-Q 2020-05-13
     ✔ inserted
  -> 8-K 2020-05-13
     ✔ inserted
  -> 8-K 2020-05-05
     ✔ inserted
  -> 8-K 2020-04-24
     ✔ inserted
  -> 8-K 2020-04-16
     ✔ inserted
  -> 8-K 2020-03-25
     ✔ inserted
  -> 8-K 2020-03-16
     ✔ inserted
  -> 8-K 2020-03-05
     ✔ inserted
  -> 10-K 2020-03-04
     ✔ inserted
  -> 8-K 2020-03-04
     ✔ inserted
  -> 8-K 2020-03-02
     ✔ inserted
  -> 8-K 2020-01-30
     ✔ inserted
  -> 8-K 2019-12-05
     ✔ inserted
  -> 8-K 2019-11-07
     ✔ inserted
  -> 10-Q 2019-11-06
     ✔ inserted
  -> 8-K 2019-11-06
     ✔ inserted
  -> 8-K 2019-10-31
     ✔ inserted
  -> 8-K 2019-09-12
     ✔ inserted
  -> 10-Q 2019-08-06
     ✔ inserted
  -> 8-K 2019-08-06
     ✔ inserted
  -> 8-K 2019-07-15
     ✔ inserted
  -> 8-K 2019-06-10
     ✔ inserted
  -> 8-K 2019-05-09
     ✔ inserted
  -> 10-Q 2019-05-08
     ✔ inserted
  -> 8-K 2019-05-08
     ✔ inserted
  -> 8-K 2019-04-12
     ✔ inserted
  -> 8-K 2019-04-02
     ✔ inserted
  -> 8-K 2019-03-21
     ✔ inserted
  -> 8-K 2019-03-11
     ✔ inserted
  -> 8-K 2019-03-07
     ✔ inserted
  -> 8-K 2019-03-06
     ✔ inserted
  -> 8-K 2019-02-28
     ✔ inserted
  -> 10-K 2019-02-27
     ✔ inserted
  -> 8-K 2019-02-27
     ✔ inserted
  -> 8-K 2019-01-25
     ✔ inserted
  -> 8-K 2018-12-13
     ✔ inserted
  -> 8-K 2018-12-07
     ✔ inserted
  -> 10-Q 2018-11-07
     ✔ inserted
  -> 8-K 2018-11-07
     ✔ inserted
  -> 8-K 2018-09-06
     ✔ inserted
  -> 10-Q 2018-08-01
     ✔ inserted
  -> 8-K 2018-08-01
     ✔ inserted
  -> 8-K 2018-06-04
     ✔ inserted
  -> 10-Q 2018-05-09
     ✔ inserted
  -> 8-K 2018-05-09
     ✔ inserted
  -> 8-K 2018-04-16
     ✔ inserted
  -> 8-K 2018-03-15
     ✔ inserted
  -> 10-K 2018-03-06
     ✔ inserted
  -> 8-K 2018-03-06
     ✔ inserted
  -> 8-K 2018-01-09
     ✔ inserted
  -> 8-K 2017-12-22
     ✔ inserted
  -> 8-K 2017-12-07
     ✔ inserted
  -> 10-Q 2017-11-01
     ✔ inserted
  -> 8-K 2017-11-01
     ✔ inserted
  -> 8-K 2017-09-18
     ✔ inserted
  -> 8-K 2017-08-31
     ✔ inserted
  -> 8-K 2017-08-09
     ✔ inserted
  -> 10-Q 2017-08-01
     ✔ inserted
  -> 8-K 2017-08-01
     ✔ inserted
  -> 8-K 2017-06-16
     ✔ inserted
  -> 8-K 2017-06-15
     ✔ inserted
  -> 10-Q 2017-05-09
     ✔ inserted
  -> 8-K 2017-05-09
     ✔ inserted
  -> 8-K 2017-03-21
     ✔ inserted
  -> 10-K 2017-03-01
     ✔ inserted
  -> 8-K 2017-03-01
     ✔ inserted
  -> 8-K 2017-02-06
     ✔ inserted
  -> 8-K 2017-01-18
     ✔ inserted
  -> 8-K 2017-01-17
     ✔ inserted
  -> 8-K 2017-01-10
     ✔ inserted
  -> 8-K 2016-12-07
     ✔ inserted
  -> 10-Q 2016-11-02
     ✔ inserted
  -> 8-K 2016-11-02
     ✔ inserted
  -> 10-Q 2016-08-03
     ✔ inserted
  -> 8-K 2016-08-03
     ✔ inserted
  -> 8-K 2016-05-19
     ✔ inserted
  -> 10-Q 2016-05-04
     ✔ inserted
  -> 8-K 2016-05-04
     ✔ inserted
  -> 10-K 2016-03-02
     ✔ inserted
  -> 8-K 2016-03-02
     ✔ inserted
  -> 8-K 2016-02-25
     ✔ inserted
  -> 8-K 2015-12-30
     ✔ inserted
  -> 8-K 2015-12-10
     ✔ inserted
  ✅ Done. Inserted 183.

=== [2/927] AMD ===

=== CIK=0000002488 ticker=AMD ===
  Found 145 filings.
  -> 10-Q 2025-11-05
     ✔ inserted
  -> 8-K 2025-11-04
     ✔ inserted
  -> 8-K 2025-10-27
     ✔ inserted
  -> 8-K 2025-10-06
     ✔ inserted
  -> 8-K 2025-08-25
     ✔ inserted
  -> 10-Q 2025-08-06
     ✔ inserted
  -> 8-K 2025-08-05
     ✔ inserted
  -> 8-K 2025-07-02
     ✔ inserted
  -> 8-K 2025-05-19
     ✔ inserted
  -> 8-K 2025-05-16
     ✔ inserted
  -> 10-Q 2025-05-07
     ✔ inserted
  -> 8-K 2025-05-06
     ✔ inserted
  -> 8-K 2025-04-16
     ✔ inserted
  -> 8-K 2025-03-31
     ✔ inserted
  -> 8-K 2025-03-24
     ✔ inserted
  -> 8-K 2025-03-12
     ✔ inserted
  -> 8-K 2025-02-24
     ✔ inserted
  -> 10-K 2025-02-05
     ✔ inserted
  -> 8-K 2025-02-04
     ✔ inserted
  -> 8-K 2024-11-18
     ✔ inserted
  -> 10-Q 2024-10-30
     ✔ inserted
  -> 8-K 2024-10-29
     ✔ inserted
  -> 8-K 2024-08-19
     ✔ inserted
  -> 10-Q 2024-07-31
     ✔ inserted
  -> 8-K 2024-07-30
     ✔ inserted
  -> 8-K 2024-07-22
     ✔ inserted
  -> 8-K 2024-07-02
     ✔ inserted
  -> 8-K 2024-05-13
     ✔ inserted
  -> 10-Q 2024-05-01
     ✔ inserted
  -> 8-K 2024-04-30
     ✔ inserted
  -> 8-K 2024-02-20
     ✔ inserted
  -> 10-K 2024-01-31
     ✔ inserted
  -> 8-K 2024-01-30
     ✔ inserted
  -> 10-Q 2023-11-01
     ✔ inserted
  -> 8-K 2023-10-31
     ✔ inserted
  -> 10-Q 2023-08-02
     ✔ inserted
  -> 8-K 2023-08-01
     ✔ inserted
  -> 8-K 2023-07-10
     ✔ inserted
  -> 8-K 2023-05-23
     ✔ inserted
  -> 10-Q 2023-05-03
     ✔ inserted
  -> 8-K 2023-05-02
     ✔ inserted
  -> 10-K 2023-02-27
     ✔ inserted
  -> 8-K 2023-02-21
     ✔ inserted
  -> 8-K 2023-01-31
     ✔ inserted
  -> 8-K 2023-01-11
     ✔ inserted
  -> 8-K 2022-11-16
     ✔ inserted
  -> 8-K 2022-11-08
     ✔ inserted
  -> 10-Q 2022-11-02
     ✔ inserted
  -> 8-K 2022-11-01
     ✔ inserted
  -> 8-K 2022-10-06
     ✔ inserted
  -> 10-Q 2022-08-03
     ✔ inserted
  -> 8-K 2022-08-02
     ✔ inserted
  -> 8-K 2022-06-28
     ✔ inserted
  -> 8-K 2022-06-09
     ✔ inserted
  -> 8-K 2022-06-08
     ✔ inserted
  -> 8-K 2022-05-20
     ✔ inserted
  -> 10-Q 2022-05-04
     ✔ inserted
  -> 8-K 2022-05-03
     ✔ inserted
  -> 8-K 2022-02-28
     ✔ inserted
  -> 8-K 2022-02-14
     ✔ inserted
  -> 8-K 2022-02-10
     ✔ inserted
  -> 10-K 2022-02-03
     ✔ inserted
  -> 8-K 2022-02-01
     ✔ inserted
  -> 8-K 2022-01-27
     ✔ inserted
  -> 8-K 2021-12-23
     ✔ inserted
  -> 10-Q 2021-10-27
     ✔ inserted
  -> 8-K 2021-10-26
     ✔ inserted
  -> 10-Q 2021-07-28
     ✔ inserted
  -> 8-K 2021-07-27
     ✔ inserted
  -> 8-K 2021-06-30
     ✔ inserted
  -> 8-K 2021-06-24
     ✔ inserted
  -> 8-K 2021-05-21
     ✔ inserted
  -> 8-K 2021-05-13
     ✔ inserted
  -> 10-Q 2021-04-28
     ✔ inserted
  -> 8-K 2021-04-27
     ✔ inserted
  -> 8-K 2021-04-08
     ✔ inserted
  -> 8-K 2021-03-08
     ✔ inserted
  -> 8-K 2021-02-22
     ✔ inserted
  -> 10-K 2021-01-29
     ✔ inserted
  -> 8-K 2021-01-26
     ✔ inserted
  -> 8-K 2021-01-12
     ✔ inserted
  -> 8-K 2021-01-06
     ✔ inserted
  -> 10-Q 2020-10-28
     ✔ inserted
  -> 8-K 2020-10-27
     ✔ inserted
  -> 8-K 2020-10-27
     ✔ inserted
  -> 8-K 2020-10-27
     ✔ inserted
  -> 8-K 2020-08-11
     ✔ inserted
  -> 10-Q 2020-07-29
     ✔ inserted
  -> 8-K 2020-07-28
     ✔ inserted
  -> 8-K 2020-05-12
     ✔ inserted
  -> 10-Q 2020-04-29
     ✔ inserted
  -> 8-K 2020-04-28
     ✔ inserted
  -> 8-K 2020-03-12
     ✔ inserted
  -> 8-K 2020-02-18
     ✔ inserted
  -> 10-K 2020-02-04
     ✔ inserted
  -> 8-K 2020-01-28
     ✔ inserted
  -> 8-K 2019-12-16
     ✔ inserted
  -> 8-K 2019-12-02
     ✔ inserted
  -> 8-K 2019-11-12
     ✔ inserted
  -> 10-Q 2019-10-30
     ✔ inserted
  -> 8-K 2019-10-29
     ✔ inserted
  -> 8-K 2019-09-06
     ✔ inserted
  -> 8-K 2019-08-08
     ✔ inserted
  -> 10-Q 2019-07-31
     ✔ inserted
  -> 8-K 2019-07-30
     ✔ inserted
  -> 8-K 2019-06-27
     ✔ inserted
  -> 8-K 2019-06-10
     ✔ inserted
  -> 8-K 2019-05-17
     ✔ inserted
  -> 10-Q 2019-05-01
     ✔ inserted
  -> 8-K 2019-04-30
     ✔ inserted
  -> 8-K 2019-02-22
     ✔ inserted
  -> 8-K 2019-02-14
     ✔ inserted
  -> 10-K 2019-02-08
     ✔ inserted
  -> 8-K 2019-01-29
     ✔ inserted
  -> 10-Q 2018-10-31
     ✔ inserted
  -> 8-K 2018-10-24
     ✔ inserted
  -> 8-K 2018-08-27
     ✔ inserted
  -> 8-K 2018-08-06
     ✔ inserted
  -> 10-Q 2018-08-02
     ✔ inserted
  -> 8-K 2018-07-25
     ✔ inserted
  -> 8-K 2018-07-02
     ✔ inserted
  -> 8-K 2018-05-08
     ✔ inserted
  -> 10-Q 2018-05-03
     ✔ inserted
  -> 8-K 2018-04-25
     ✔ inserted
  -> 8-K 2018-03-05
     ✔ inserted
  -> 8-K 2018-02-27
     ✔ inserted
  -> 10-K 2018-02-27
     ✔ inserted
  -> 8-K 2018-02-12
     ✔ inserted
  -> 8-K 2018-01-30
     ✔ inserted
  -> 10-Q 2017-11-02
     ✔ inserted
  -> 8-K 2017-11-01
     ✔ inserted
  -> 8-K 2017-10-24
     ✔ inserted
  -> 8-K 2017-08-07
     ✔ inserted
  -> 10-Q 2017-08-03
     ✔ inserted
  -> 8-K 2017-07-25
     ✔ inserted
  -> 8-K 2017-07-03
     ✔ inserted
  -> 10-Q 2017-05-08
     ✔ inserted
  -> 8-K 2017-05-01
     ✔ inserted
  -> 8-K 2017-04-28
     ✔ inserted
  -> 8-K 2017-03-21
     ✔ inserted
  -> 8-K 2017-03-02
     ✔ inserted
  -> 10-K 2017-02-21
     ✔ inserted
  -> 8-K 2017-02-21
     ✔ inserted
  -> 8-K 2017-02-21
     ✔ inserted
  -> 8-K 2017-01-31
     ✔ inserted
  ✅ Done. Inserted 145.

=== [3/927] SWKS ===

=== CIK=0000004127 ticker=SWKS ===
  Found 137 filings.
  -> 8-K 2025-11-24
     ✔ inserted
  -> 8-K 2025-11-14
     ✔ inserted
  -> 10-K 2025-11-07
     ✔ inserted
  -> 8-K 2025-11-04
     ✔ inserted
  -> 8-K 2025-10-28
     ✔ inserted
  -> 8-K 2025-10-28
     ✔ inserted
  -> 8-K 2025-08-25
     ✔ inserted
  -> 10-Q 2025-08-05
     ✔ inserted
  -> 8-K 2025-08-05
     ✔ inserted
  -> 8-K 2025-05-29
     ✔ inserted
  -> 8-K 2025-05-16
     ✔ inserted
  -> 10-Q 2025-05-07
     ✔ inserted
  -> 8-K 2025-05-07
     ✔ inserted
  -> 8-K 2025-05-07
     ✔ inserted
  -> 8-K 2025-04-30
     ✔ inserted
  -> 8-K 2025-03-14
     ✔ inserted
  -> 8-K 2025-02-06
     ✔ inserted
  -> 10-Q 2025-02-05
     ✔ inserted
  -> 8-K 2025-02-05
     ✔ inserted
  -> 8-K 2024-12-13
     ✔ inserted
  -> 10-K 2024-11-15
     ✔ inserted
  -> 8-K 2024-11-12
     ✔ inserted
  -> 10-Q 2024-07-31
     ✔ inserted
  -> 8-K 2024-07-30
     ✔ inserted
  -> 8-K 2024-05-17
     ✔ inserted
  -> 10-Q 2024-05-01
     ✔ inserted
  -> 8-K 2024-04-30
     ✔ inserted
  -> 10-Q 2024-01-31
     ✔ inserted
  -> 8-K 2024-01-30
     ✔ inserted
  -> 8-K 2023-12-15
     ✔ inserted
  -> 10-K 2023-11-17
     ✔ inserted
  -> 8-K 2023-11-02
     ✔ inserted
  -> 10-Q 2023-08-08
     ✔ inserted
  -> 8-K 2023-08-07
     ✔ inserted
  -> 8-K 2023-05-16
     ✔ inserted
  -> 8-K 2023-05-12
     ✔ inserted
  -> 10-Q 2023-05-09
     ✔ inserted
  -> 8-K 2023-05-08
     ✔ inserted
  -> 8-K 2023-03-10
     ✔ inserted
  -> 8-K 2023-02-09
     ✔ inserted
  -> 10-Q 2023-02-07
     ✔ inserted
  -> 8-K 2023-02-06
     ✔ inserted
  -> 8-K 2023-02-06
     ✔ inserted
  -> 8-K 2022-12-16
     ✔ inserted
  -> 10-K 2022-11-23
     ✔ inserted
  -> 8-K 2022-11-03
     ✔ inserted
  -> 10-Q 2022-08-05
     ✔ inserted
  -> 8-K 2022-08-04
     ✔ inserted
  -> 8-K 2022-05-13
     ✔ inserted
  -> 10-Q 2022-05-04
     ✔ inserted
  -> 8-K 2022-05-03
     ✔ inserted
  -> 10-Q 2022-02-04
     ✔ inserted
  -> 8-K 2022-02-03
     ✔ inserted
  -> 8-K 2022-02-02
     ✔ inserted
  -> 8-K 2021-12-17
     ✔ inserted
  -> 10-K 2021-11-24
     ✔ inserted
  -> 8-K 2021-11-04
     ✔ inserted
  -> 10-Q 2021-07-30
     ✔ inserted
  -> 8-K 2021-07-29
     ✔ inserted
  -> 8-K 2021-07-26
     ✔ inserted
  -> 8-K 2021-06-08
     ✔ inserted
  -> 8-K 2021-05-26
     ✔ inserted
  -> 8-K 2021-05-17
     ✔ inserted
  -> 8-K 2021-05-14
     ✔ inserted
  -> 8-K 2021-05-13
     ✔ inserted
  -> 10-Q 2021-04-30
     ✔ inserted
  -> 8-K 2021-04-29
     ✔ inserted
  -> 8-K 2021-04-22
     ✔ inserted
  -> 8-K 2021-02-16
     ✔ inserted
  -> 10-Q 2021-01-29
     ✔ inserted
  -> 8-K 2021-01-28
     ✔ inserted
  -> 8-K 2021-01-28
     ✔ inserted
  -> 8-K 2020-12-18
     ✔ inserted
  -> 10-K 2020-11-17
     ✔ inserted
  -> 8-K 2020-11-02
     ✔ inserted
  -> 10-Q 2020-07-24
     ✔ inserted
  -> 8-K 2020-07-23
     ✔ inserted
  -> 8-K 2020-05-08
     ✔ inserted
  -> 10-Q 2020-05-05
     ✔ inserted
  -> 8-K 2020-05-04
     ✔ inserted
  -> 8-K 2020-04-14
     ✔ inserted
  -> 8-K 2020-03-04
     ✔ inserted
  -> 10-Q 2020-01-24
     ✔ inserted
  -> 8-K 2020-01-23
     ✔ inserted
  -> 8-K 2019-12-20
     ✔ inserted
  -> 10-K 2019-11-14
     ✔ inserted
  -> 8-K 2019-11-12
     ✔ inserted
  -> 8-K 2019-08-26
     ✔ inserted
  -> 10-Q 2019-08-07
     ✔ inserted
  -> 8-K 2019-08-07
     ✔ inserted
  -> 8-K 2019-06-04
     ✔ inserted
  -> 8-K 2019-05-10
     ✔ inserted
  -> 10-Q 2019-05-03
     ✔ inserted
  -> 8-K 2019-05-02
     ✔ inserted
  -> 10-Q 2019-02-06
     ✔ inserted
  -> 8-K 2019-02-05
     ✔ inserted
  -> 8-K 2019-02-05
     ✔ inserted
  -> 8-K 2019-01-08
     ✔ inserted
  -> 10-K 2018-11-15
     ✔ inserted
  -> 8-K 2018-11-13
     ✔ inserted
  -> 8-K 2018-11-08
     ✔ inserted
  -> 8-K 2018-08-06
     ✔ inserted
  -> 8-K 2018-07-23
     ✔ inserted
  -> 10-Q 2018-07-20
     ✔ inserted
  -> 8-K 2018-07-19
     ✔ inserted
  -> 8-K 2018-05-11
     ✔ inserted
  -> 10-Q 2018-05-04
     ✔ inserted
  -> 8-K 2018-05-03
     ✔ inserted
  -> 8-K 2018-02-14
     ✔ inserted
  -> 10-Q 2018-02-05
     ✔ inserted
  -> 8-K 2018-02-05
     ✔ inserted
  -> 10-K 2017-11-13
     ✔ inserted
  -> 8-K 2017-11-09
     ✔ inserted
  -> 8-K 2017-11-06
     ✔ inserted
  -> 10-Q 2017-07-27
     ✔ inserted
  -> 8-K 2017-07-20
     ✔ inserted
  -> 8-K 2017-05-12
     ✔ inserted
  -> 10-Q 2017-05-03
     ✔ inserted
  -> 8-K 2017-04-27
     ✔ inserted
  -> 10-Q 2017-02-07
     ✔ inserted
  -> 8-K 2017-02-03
     ✔ inserted
  -> 8-K 2017-01-19
     ✔ inserted
  -> 8-K 2017-01-19
     ✔ inserted
  -> 10-K 2016-11-22
     ✔ inserted
  -> 8-K 2016-11-10
     ✔ inserted
  -> 8-K 2016-11-03
     ✔ inserted
  -> 8-K 2016-08-29
     ✔ inserted
  -> 10-Q 2016-08-03
     ✔ inserted
  -> 8-K 2016-08-03
     ✔ inserted
  -> 8-K 2016-07-21
     ✔ inserted
  -> 8-K 2016-07-21
     ✔ inserted
  -> 8-K 2016-05-16
     ✔ inserted
  -> 8-K 2016-05-12
     ✔ inserted
  -> 10-Q 2016-05-04
     ✔ inserted
  -> 8-K 2016-04-28
     ✔ inserted
  -> 10-Q 2016-02-03
     ✔ inserted
  -> 8-K 2016-01-28
     ✔ inserted
  ✅ Done. Inserted 137.

=== [4/927] ADI ===

=== CIK=0000006281 ticker=ADI ===
  Found 137 filings.
  -> 10-K 2025-11-25
     ✔ inserted
  -> 8-K 2025-11-25
     ✔ inserted
  -> 8-K 2025-09-19
     ✔ inserted
  -> 10-Q 2025-08-20
     ✔ inserted
  -> 8-K 2025-08-20
     ✔ inserted
  -> 8-K 2025-06-16
     ✔ inserted
  -> 8-K 2025-05-27
     ✔ inserted
  -> 10-Q 2025-05-22
     ✔ inserted
  -> 8-K 2025-05-22
     ✔ inserted
  -> 8-K 2025-04-11
     ✔ inserted
  -> 8-K 2025-03-13
     ✔ inserted
  -> 10-Q 2025-02-19
     ✔ inserted
  -> 8-K 2025-02-19
     ✔ inserted
  -> 8-K 2025-01-13
     ✔ inserted
  -> 10-K 2024-11-26
     ✔ inserted
  -> 8-K 2024-11-26
     ✔ inserted
  -> 8-K 2024-11-20
     ✔ inserted
  -> 8-K 2024-11-04
     ✔ inserted
  -> 8-K 2024-10-10
     ✔ inserted
  -> 8-K 2024-09-27
     ✔ inserted
  -> 10-Q 2024-08-21
     ✔ inserted
  -> 8-K 2024-08-21
     ✔ inserted
  -> 10-Q 2024-05-22
     ✔ inserted
  -> 8-K 2024-05-22
     ✔ inserted
  -> 8-K 2024-04-03
     ✔ inserted
  -> 8-K 2024-03-14
     ✔ inserted
  -> 10-Q 2024-02-21
     ✔ inserted
  -> 8-K 2024-02-21
     ✔ inserted
  -> 8-K 2024-01-25
     ✔ inserted
  -> 8-K 2024-01-19
     ✔ inserted
  -> 8-K 2023-12-07
     ✔ inserted
  -> 10-K 2023-11-21
     ✔ inserted
  -> 8-K 2023-11-21
     ✔ inserted
  -> 8-K 2023-10-13
     ✔ inserted
  -> 8-K 2023-10-04
     ✔ inserted
  -> 10-Q 2023-08-23
     ✔ inserted
  -> 8-K 2023-08-23
     ✔ inserted
  -> 8-K 2023-06-05
     ✔ inserted
  -> 10-Q 2023-05-24
     ✔ inserted
  -> 8-K 2023-05-24
     ✔ inserted
  -> 8-K 2023-05-18
     ✔ inserted
  -> 8-K 2023-04-17
     ✔ inserted
  -> 8-K 2023-03-24
     ✔ inserted
  -> 8-K 2023-03-10
     ✔ inserted
  -> 10-Q 2023-02-15
     ✔ inserted
  -> 8-K 2023-02-15
     ✔ inserted
  -> 8-K 2023-01-20
     ✔ inserted
  -> 8-K 2022-12-08
     ✔ inserted
  -> 10-K 2022-11-22
     ✔ inserted
  -> 8-K 2022-11-22
     ✔ inserted
  -> 8-K 2022-10-07
     ✔ inserted
  -> 8-K 2022-10-06
     ✔ inserted
  -> 8-K 2022-09-22
     ✔ inserted
  -> 8-K 2022-09-15
     ✔ inserted
  -> 8-K 2022-09-08
     ✔ inserted
  -> 10-Q 2022-08-17
     ✔ inserted
  -> 8-K 2022-08-17
     ✔ inserted
  -> 8-K 2022-06-27
     ✔ inserted
  -> 10-Q 2022-05-18
     ✔ inserted
  -> 8-K 2022-05-18
     ✔ inserted
  -> 8-K 2022-03-11
     ✔ inserted
  -> 8-K 2022-03-07
     ✔ inserted
  -> 8-K 2022-03-07
     ✔ inserted
  -> 10-Q 2022-02-16
     ✔ inserted
  -> 8-K 2022-02-16
     ✔ inserted
  -> 8-K 2022-01-21
     ✔ inserted
  -> 10-K 2021-12-03
     ✔ inserted
  -> 8-K 2021-11-23
     ✔ inserted
  -> 8-K 2021-10-05
     ✔ inserted
  -> 8-K 2021-10-05
     ✔ inserted
  -> 8-K 2021-09-29
     ✔ inserted
  -> 8-K 2021-09-28
     ✔ inserted
  -> 8-K 2021-09-08
     ✔ inserted
  -> 8-K 2021-08-26
     ✔ inserted
  -> 8-K 2021-08-23
     ✔ inserted
  -> 10-Q 2021-08-18

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

     ✔ inserted
  -> 8-K 2023-11-13
     ✔ inserted
  -> 10-Q 2023-11-08
     ✔ inserted
  -> 8-K 2023-11-07
     ✔ inserted
  -> 10-Q 2023-08-09
     ✔ inserted
  -> 8-K 2023-08-08
     ✔ inserted
  -> 8-K 2023-06-20
     ✔ inserted
  -> 10-Q 2023-05-10
     ✔ inserted
  -> 8-K 2023-05-09
     ✔ inserted
  -> 8-K 2023-04-24
     ✔ inserted
  -> 8-K 2023-03-09
     ✔ inserted
  -> 10-K 2023-03-01
     ✔ inserted
  -> 8-K 2023-02-28
     ✔ inserted
  -> 10-Q 2022-11-10
     ✔ inserted
  -> 8-K 2022-11-09
     ✔ inserted
  -> 8-K 2022-09-28
     ✔ inserted
  -> 10-Q 2022-08-11
     ✔ inserted
  -> 8-K 2022-08-10
     ✔ inserted
  -> 8-K 2022-07-15
     ✔ inserted
  -> 8-K 2021-06-07
     ✔ inserted
  -> 8-K 2021-06-03
     ✔ inserted
  -> 8-K 2021-05-04
     ✔ inserted
  -> 8-K 2021-05-03
     ✔ inserted
  -> 8-K 2021-04-21
     ✔ inserted
  ✅ Done. Inserted 84.

=== [715/927] KVYO ===

=== CIK=0001835830 ticker=KVYO ===
  Found 27 filings.
  -> 10-Q 2025-11-05
     ✔ inserted
  -> 8-K 2025-11-05
     ✔ inserted
  -> 8-K 2025-09-25
     ✔ inserted
  -> 8-K 2025-08-29
     ✔ inserted
  -> 8-K 2025-08-15
     ✔ inserted
  -> 10-Q 2025-08-05
     ✔ inserted
  -> 8-K 2025-08-05
     ✔ inserted
  -> 8-K 2025-08-05
     ✔ inserted
  -> 8-K 2025-06-11
     ✔ inserted
  -> 8-K 2025-05-16
     ✔ inserted
  -> 10-Q 2025-05-06
     ✔ inserted
  -> 8-K 2025-05-06
     ✔ inserted
  -> 10-K 2025-02-19
     ✔ inserted
  -> 8-K 2025-02-19
     ✔ inserted
  -> 8-K 2024-12-03
     ✔ inserted
  -> 10-Q 2024-11-06
     ✔ inserted
  -> 8-K 2024-11-06
     ✔ inserted
  -> 10-Q 2024-08-07
     ✔ inserted
  -> 8-K 2024-08-07
     ✔ inserted
  -> 8-K 2024-06-13
     ✔ inserted
  -> 10-Q 2024-05-08
     ✔ inserted
  -> 8-K 2024-05-08
     ✔ inserted
  -> 10-K 2024-02-29
     ✔ inserted
  -> 8-K 2024-02-27
     ✔ inserted
  -> 8-K 2023-11-29
     ✔ inserted
  -> 10-Q 2023-11-07
     ✔ inserted
  -> 8-K 2023-11-07
     ✔ inserted
  ✅ Done. Inserted 27.

=== [716/927] GLBE ===

=== CIK=0001835963 ticker=GLBE ===
  Found 0 filings.
  ✅ Done. Inserted 0.

=== [717/927] SRAD ===

=== CIK=0001836470 ticker=SRAD ===
  Found 0 filings.
  ✅ Done. Inserted 0.

=== [718/927] PL ===

=== CIK=0001836833 ticker=PL ===
  Found 62 filings.
  -> 8-K 2025-09-12
     ✔ inserted
  -> 8-K 2025-09-10
     ✔ inserted
  -> 10-Q 2025-09-08
     ✔ inserted
  -> 8-K 2025-09-08
     ✔ inserted
  -> 8-K 2025-07-11
     ✔ inserted
  -> 8-K 2025-07-01
     ✔ inserted
  -> 10-Q 2025-06-04
     ✔ inserted
  -> 8-K 2025-06-04
     ✔ inserted
  -> 8-K 2025-05-29
     ✔ inserted
  -> 10-K 2025-03-26
     ✔ inserted
  -> 8-K 2025-03-20
     ✔ inserted
  -> 8-K 2025-01-29
     ✔ inserted
  -> 8-K 2025-01-16
     ✔ inserted
  -> 10-Q 2024-12-09
     ✔ inserted
  -> 8-K 2024-12-09
     ✔ inserted
  -> 10-Q 2024-09-05
     ✔ inserted
  -> 8-K 2024-09-05
     ✔ inserted
  -> 8-K 2024-07-11
     ✔ inserted
  -> 8-K 2024-06-26
     ✔ inserted
  -> 10-Q 2024-06-06
     ✔ inserted
  -> 8-K 2024-06-06
     ✔ inserted
  -> 8-K 2024-05-09
     ✔ inserted
  -> 8-K 2024-04-05
     ✔ inserted
  -> 10-K 2024-03-29
     ✔ inserted
  -> 8-K 2024-03-28
     ✔ inserted
  -> 10-Q 2023-12-08
     ✔ inserted
  -> 8-K 2023-12-07
     ✔ inserted
  -> 10-Q 2023-09-07
     ✔ inserted
  -> 8-K 2023-09-07
     ✔ inserted
  -> 8-K 2023-08-01
     ✔ inserted
  -> 8-K 2023-07-11
     ✔ inserted
  -> 10-Q 2023-06-09
     ✔ inserted
  -> 8-K 2023-06-08
     ✔ inserted
  -> 8-K 2023-04-25
     ✔ inserted
  -> 8-K 2023-04-17
     ✔ inserted
  -> 10-K 2023-03-30
     ✔ inserted
  -> 8-K 2023-03-29
     ✔ inserted
  -> 10-Q 2022-12-14
     ✔ inserted
  -> 8-K 2022-12-14
     ✔ inserted
  -> 8-K 2022-11-09
     ✔ inserted
  -> 8-K 2022-09-12
     ✔ inserted
  -> 10-Q 2022-09-12
     ✔ inserted
  -> 8-K 2022-09-08
     ✔ inserted
  -> 8-K 2022-07-20
     ✔ inserted
  -> 8-K 2022-06-14
     ✔ inserted
  -> 10-Q 2022-06-14
     ✔ inserted
  -> 10-K 2022-04-14
     ✔ inserted
  -> 8-K 2022-03-31
     ✔ inserted
  -> 8-K 2021-12-13
     ✔ inserted
  -> 8-K 2021-12-13
     ✔ inserted
  -> 8-K 2021-12-06
     ✔ inserted
  -> 8-K 2021-11-26
     ✔ inserted
  -> 10-Q 2021-11-15
     ✔ inserted
  -> 8-K 2021-11-09
     ✔ inserted
  -> 8-K 2021-09-16
     ✔ inserted
  -> 10-Q 2021-08-16
     ✔ inserted
  -> 8-K 2021-07-07
     ✔ inserted
  -> 10-Q 2021-06-04
     ✔ inserted
  -> 8-K 2021-06-01
     ✔ inserted
  -> 8-K 2021-04-23
     ✔ inserted
  -> 8-K 2021-03-15
     ✔ inserted
  -> 8-K 2021-03-09
     ✔ inserted
  ✅ Done. Inserted 62.

=== [719/927] ZENV ===

=== CIK=0001836934 ticker=ZENV ===
  Found 0 filings.
  ✅ Done. Inserted 0.

=== [720/927] BBAI ===

=== CIK=0001836981 ticker=BBAI ===
  Found 94 filings.
  -> 10-Q 2025-11-10
     ✔ inserted
  -> 8-K 2025-11-10
     ✔ inserted
  -> 8-K 2025-10-14
     ✔ inserted
  -> 8-K 2025-08-15
     ✔ inserted
  -> 10-Q 2025-08-11
     ✔ inserted
  -> 8-K 2025-08-11
     ✔ inserted
  -> 8-K 2025-07-17
     ✔ inserted
  -> 8-K 2025-06-06
     ✔ inserted
  -> 8-K 2025-06-02
     ✔ inserted
  -> 8-K 2025-06-02
     ✔ inserted
  -> 8-K 2025-05-15
     ✔ inserted
  -> 10-Q 2025-05-02
     ✔ inserted
  -> 8-K 2025-05-01
     ✔ inserted
  -> 8-K 2025-04-14
     ✔ inserted
  -> 8-K 2025-03-27
     ✔ inserted
  -> 10-K 2025-03-25
     ✔ inserted
  -> 8-K 2025-03-18
     ✔ inserted
  -> 8-K 2025-03-06
     ✔ inserted
  -> 8-K 2025-02-06
     ✔ inserted
  -> 8-K 2025-01-16
     ✔ inserted
  -> 8-K 2025-01-15
     ✔ inserted
  -> 8-K 2024-12-30
     ✔ inserted
  -> 8-K 2024-12-19
     ✔ inserted
  -> 10-Q 2024-11-07
     ✔ inserted
  -> 8-K 2024-11-05
     ✔ inserted
  -> 8-K 2024-10-04
     ✔ inserted
  -> 10-Q 2024-08-09
     ✔ inserted
  -> 8-K 2024-08-01
     ✔ inserted
  -> 8-K 2024-06-03
     ✔ inserted
  -> 10-Q 2024-05-10
     ✔ inserted
  -> 8-K 2024-05-02
     ✔ inserted
  -> 8-K 2024-03-28
     ✔ inserted
  -> 8-K 2024-03-27
     ✔ inserted
  -> 10-K 2024-03-15
     ✔ inserted
  -> 8-K 2024-03-07
     ✔ inserted
  -> 8-K 2024-03-05
     ✔ inserted
  -> 8-K 2024-03-01
     ✔ inserted
  -> 8-K 2024-02-28
     ✔ inserted
  -> 8-K 2024-02-27
     ✔ inserted
  -> 8-K 2024-02-22
     ✔ inserted
  -> 8-K 2024-02-22
     ✔ inserted
  -> 8-K 2024-02-06
     ✔ inserted
  -> 10-Q 2023-11-09
     ✔ inserted
  -> 8-K 2023-11-07
     ✔ inserted
  -> 8-K 2023-11-06
     ✔ inserted
  -> 10-Q 2023-08-10
     ✔ inserted
  -> 8-K 2023-08-08
     ✔ inserted
  -> 8-K 2023-06-26
     ✔ inserted
  -> 8-K 2023-06-12
     ✔ inserted
  -> 8-K 2023-06-08
     ✔ inserted
  -> 8-K 2023-05-17
     ✔ inserted
  -> 10-Q 2023-05-15
     ✔ inserted
  -> 8-K 2023-05-09
     ✔ inserted
  -> 10-K 2023-03-31
     ✔ inserted
  -> 8-K 2023-03-24
     ✔ inserted
  -> 8-K 2023-03-13
     ✔ inserted
  -> 8-K 2023-01-19
     ✔ inserted
  -> 8-K 2023-01-04
     ✔ inserted
  -> 8-K 2022-12-23
     ✔ inserted
  -> 8-K 2022-11-21
     ✔ inserted
  -> 10-Q 2022-11-10
     ✔ inserted
  -> 8-K 2022-11-09
     ✔ inserted
  -> 8-K 2022-10-11
     ✔ inserted
  -> 8-K 2022-09-20
     ✔ inserted
  -> 8-K 2022-09-01
     ✔ inserted
  -> 10-Q 2022-08-12
     ✔ inserted
  -> 8-K 2022-08-09
     ✔ inserted
  -> 8-K 2022-06-23
     ✔ inserted
  -> 8-K 2022-06-02
     ✔ inserted
  -> 8-K 2022-05-31
     ✔ inserted
  -> 10-Q 2022-05-12
     ✔ inserted
  -> 8-K 2022-05-09
     ✔ inserted
  -> 10-K 2022-03-31
     ✔ inserted
  -> 8-K 2022-03-17
     ✔ inserted
  -> 8-K 2022-02-23
     ✔ inserted
  -> 8-K 2021-12-13
     ✔ inserted
  -> 8-K 2021-12-07
     ✔ inserted
  -> 8-K 2021-12-07
     ✔ inserted
  -> 8-K 2021-12-06
     ✔ inserted
  -> 8-K 2021-12-03
     ✔ inserted
  -> 8-K 2021-11-30
     ✔ inserted
  -> 8-K 2021-11-26
     ✔ inserted
  -> 10-Q 2021-11-15
     ✔ inserted
  -> 8-K 2021-10-22
     ✔ inserted
  -> 8-K 2021-10-15
     ✔ inserted
  -> 10-Q 2021-08-16
     ✔ inserted
  -> 8-K 2021-07-16
     ✔ inserted
  -> 8-K 2021-06-08
     ✔ inserted
  -> 8-K 2021-06-04
     ✔ inserted
  -> 10-Q 2021-05-17
     ✔ inserted
  -> 10-K 2021-03-31
     ✔ inserted
  -> 8-K 2021-03-26
     ✔ inserted
  -> 8-K 2021-02-18
     ✔ inserted
  -> 8-K 2021-02-12
     ✔ inserted
  ✅ Done. Inserted 94.

=== [721/927] SMRT ===

=== CIK=0001837014 ticker=SMRT ===
  Found 71 filings.
  -> 8-K 2025-11-17
     ✔ inserted
  -> 10-Q 2025-11-05
     ✔ inserted
  -> 8-K 2025-11-05
     ✔ inserted
  -> 10-Q 2025-08-06
     ✔ inserted
  -> 8-K 2025-08-06
     ✔ inserted
  -> 8-K 2025-06-24
     ✔ inserted
  -> 8-K 2025-06-16
     ✔ inserted
  -> 8-K 2025-05-19
     ✔ inserted
  -> 10-Q 2025-05-07
     ✔ inserted
  -> 8-K 2025-05-07
     ✔ inserted
  -> 8-K 2025-05-05
     ✔ inserted
  -> 8-K 2025-04-10
     ✔ inserted
  -> 10-K 2025-03-05
     ✔ inserted
  -> 8-K 2025-03-05
     ✔ inserted
  -> 8-K 2025-02-03
     ✔ inserted
  -> 8-K 2025-01-27
     ✔ inserted
  -> 10-Q 2024-11-06
     ✔ inserted
  -> 8-K 2024-11-06
     ✔ inserted
  -> 10-Q 2024-08-07
     ✔ inserted
  -> 8-K 2024-08-07
     ✔ inserted
  -> 8-K 2024-07-31
     ✔ inserted
  -> 8-K 2024-07-30
     ✔ inserted
  -> 8-K 2024-06-21
     ✔ inserted
  -> 8-K 2024-05-15
     ✔ inserted
  -> 10-Q 2024-05-08
     ✔ inserted
  -> 8-K 2024-05-08
     ✔ inserted
  -> 8-K 2024-03-22
     ✔ inserted
  -> 10-K 2024-03-05
     ✔ inserted
  -> 8-K 2024-03-05
     ✔ inserted
  -> 8-K 2024-01-25
     ✔ inserted
  -> 8-K 2023-12-06
     ✔ inserted
  -> 8-K 2023-11-15
     ✔ inserted
  -> 10-Q 2023-11-07
     ✔ inserted
  -> 8-K 2023-11-07
     ✔ inserted
  -> 10-Q 2023-08-08
     ✔ inserted
  -> 8-K 2023-08-08
     ✔ inserted
  -> 8-K 2023-08-08
     ✔ inserted
  -> 8-K 2023-05-17
     ✔ inserted
  -> 10-Q 2023-05-10
     ✔ inserted
  -> 8-K 2023-05-10
     ✔ inserted
  -> 10-K 2023-03-08
     ✔ inserted
  -> 8-K 2023-03-08
     ✔ inserted
  -> 8-K 2022-11-10
     ✔ inserted
  -> 10-Q 2022-11-10
     ✔ inserted
  -> 10-Q 2022-08-11
     ✔ inserted
  -> 8-K 2022-08-11
     ✔ inserted
  -> 8-K 2022-07-25
     ✔ inserted
  -> 8-K 2022-05-18
     ✔ inserted
  -> 10-Q 2022-05-11
     ✔ inserted
  -> 8-K 2022-05-11
     ✔ inserted
  -> 8-K 2022-04-28
     ✔ inserted
  -> 10-K 2022-03-25
     ✔ inserted
  -> 8-K 2022-03-24
     ✔ inserted
  -> 8-K 2022-01-11
     ✔ inserted
  -> 8-K 2021-12-13
     ✔ inserted
  -> 8-K 2021-11-18
     ✔ inserted
  -> 10-Q 2021-11-10
     ✔ inserted
  -> 8-K 2021-11-10
     ✔ inserted
  -> 8-K 2021-09-08
     ✔ inserted
  -> 8-K 2021-08-30
     ✔ inserted
  -> 8-K 2021-08-25
     ✔ inserted
  -> 8-K 2021-08-24
     ✔ inserted
  -> 8-K 2021-08-17
     ✔ inserted
  -> 8-K 2021-08-13
     ✔ inserted
  -> 10-Q 2021-08-13
     ✔ inserted
  -> 8-K 2021-08-06
     ✔ inserted
  -> 8-K 2021-07-26
     ✔ inserted
  -> 10-Q 2021-05-17
     ✔ inserted
  -> 8-K 2021-04-22
     ✔ inserted
  -> 8-K 2021-02-16
     ✔ inserted
  -> 8-K 2021-02-10
     ✔ inserted
  ✅ Done. Inserted 71.

=== [722/927] VMEO ===

=== CIK=0001837686 ticker=VMEO ===
  Found 84 filings.
  -> 8-K 2025-11-24
     ✔ inserted
  -> 8-K 2025-11-19
     ✔ inserted
  -> 8-K 2025-11-18
     ✔ inserted
  -> 8-K 2025-11-07
     ✔ inserted
  -> 10-Q 2025-10-28
     ✔ inserted
  -> 8-K 2025-10-06
     ✔ inserted
  -> 8-K 2025-09-11
     ✔ inserted
  -> 8-K 2025-09-10
     ✔ inserted
  -> 8-K 2025-09-03
     ✔ inserted
  -> 8-K 2025-08-29
     ✔ inserted
  -> 10-Q 2025-08-04
     ✔ inserted
  -> 8-K 2025-08-04
     ✔ inserted
  -> 8-K 2025-06-16
     ✔ inserted
  -> 8-K 2025-06-10
     ✔ inserted
  -> 10-Q 2025-05-05
     ✔ inserted
  -> 8-K 2025-05-05
     ✔ inserted
  -> 10-K 2025-02-19
     ✔ inserted
  -> 8-K 2025-02-19
     ✔ inserted
  -> 10-Q 2024-11-05
     ✔ inserted
  -> 8-K 2024-11-04
     ✔ inserted
  -> 10-Q 2024-08-06
     ✔ inserted
  -> 8-K 2024-08-05
     ✔ inserted
  -> 8-K 2024-05-22
     ✔ inserted
  -> 10-Q 2024-05-07
     ✔ inserted
  -> 8-K 2024-05-06
     ✔ inserted
  -> 8-K 2024-04-04
     ✔ inserted
  -> 10-K 2024-02-22
     ✔ inserted
  -> 8-K 2024-02-21
     ✔ inserted
  -> 10-Q 2023-11-07
     ✔ inserted
  -> 8-K 2023-11-06
     ✔ inserted
  -> 8-K 2023-10-23
     ✔ inserted
  -> 10-Q 2023-08-02
     ✔ inserted
  -> 8-K 2023-08-01
     ✔ inserted
  -> 8-K 2023-07-05
     ✔ inserted
  -> 8-K 2023-06-08
     ✔ inserted
  -> 10-Q 2023-05-04
     ✔ inserted
  -> 8-K 2023-05-03
     ✔ inserted
  -> 8-K 2023-03-23
     ✔ inserted
  -> 8-K 2023-03-10
     ✔ inserted
  -> 10-K 2023-02-27
     ✔ inserted
  -> 8-K 2023-02-27
     ✔ inserted
  -> 8-K 2023-02-21
     ✔ inserted
  -> 8-K 2023-01-18
     ✔ inserted
  -> 8-K 2023-01-04
     ✔ inserted
  -> 8-K 2022-12-20
     ✔ inserted
  -> 8-K 2022-12-15
     ✔ inserted
  -> 8-K 2022-11-15
     ✔ inserted
  -> 10-Q 2022-11-03
     ✔ inserted
  -> 8-K 2022-11-02
     ✔ inserted
  -> 8-K 2022-10-18
     ✔ inserted
  -> 8-K 2022-09-14
     ✔ inserted
  -> 8-K 2022-08-15
     ✔ inserted
  -> 10-Q 2022-08-04
     ✔ inserted
  -> 8-K 2022-08-03
     ✔ inserted
  -> 8-K 2022-07-19
     ✔ inserted
  -> 8-K 2022-06-16
     ✔ inserted
  -> 8-K 2022-06-15
     ✔ inserted
  -> 8-K 2022-06-08
     ✔ inserted
  -> 8-K 2022-05-17
     ✔ inserted
  -> 10-Q 2022-05-05
     ✔ inserted
  -> 8-K 2022-05-04
     ✔ inserted
  -> 8-K 2022-04-11
     ✔ inserted
  -> 8-K 2022-04-04
     ✔ inserted
  -> 8-K 2022-03-14
     ✔ inserted
  -> 10-K 2022-03-01
     ✔ inserted
  -> 8-K 2022-02-14
     ✔ inserted
  -> 8-K 2022-02-09
     ✔ inserted
  -> 8-K 2022-01-18
     ✔ inserted
  -> 8-K 2021-12-20
     ✔ inserted
  -> 8-K 2021-12-13
     ✔ inserted
  -> 8-K 2021-11-08
     ✔ inserted
  -> 10-Q 2021-11-05
     ✔ inserted
  -> 8-K 2021-11-03
     ✔ inserted
  -> 8-K 2021-10-12
     ✔ inserted
  -> 8-K 2021-09-13
     ✔ inserted
  -> 10-Q 2021-08-06
     ✔ inserted
  -> 8-K 2021-08-05
     ✔ inserted
  -> 8-K 2021-07-12
     ✔ inserted
  -> 8-K 2021-06-14
     ✔ inserted
  -> 8-K 2021-06-08
     ✔ inserted
  -> 8-K 2021-05-27
     ✔ inserted
  -> 8-K 2021-05-26
     ✔ inserted
  -> 10-Q 2021-05-10
     ✔ inserted
  -> 8-K 2021-05-05
     ✔ inserted
  ✅ Done. Inserted 84.

=== [723/927] BNAI ===

=== CIK=0001838163 ticker=BNAI ===
  Found 74 filings.
  -> 8-K 2025-11-28
     ✔ inserted
  -> 10-Q 2025-11-25
     ✔ inserted
  -> 8-K 2025-11-10
     ✔ inserted
  -> 8-K 2025-10-14
     ✔ inserted
  -> 10-Q 2025-10-14
     ✔ inserted
  -> 8-K 2025-09-19
     ✔ inserted
  -> 8-K 2025-09-12
     ✔ inserted
  -> 8-K 2025-08-27
     ✔ inserted
  -> 8-K 2025-08-18
     ✔ inserted
  -> 8-K 2025-07-21
     ✔ inserted
  -> 8-K 2025-07-15
     ✔ inserted
  -> 8-K 2025-07-02
     ✔ inserted
  -> 8-K 2025-06-24
     ✔ inserted
  -> 8-K 2025-06-10
     ✔ inserted
  -> 10-Q 2025-06-05
     ✔ inserted
  -> 8-K 2025-05-30
     ✔ inserted
  -> 8-K 2025-05-23
     ✔ inserted
  -> 10-K 2025-03-31
     ✔ inserted
  -> 8-K 2025-03-28
     ✔ inserted
  -> 8-K 2025-02-12
     ✔ inserted
  -> 8-K 2025-01-17
     ✔ inserted
  -> 8-K 2025-01-14
     ✔ inserted
  -> 8-K 2025-01-06
     ✔ inserted
  -> 10-Q 2024-11-14
     ✔ inserted
  -> 8-K 2024-11-14
     ✔ inserted
  -> 8-K 2024-11-08
     ✔ inserted
  -> 8-K 2024-11-07
     ✔ inserted
  -> 8-K 2024-10-30
     ✔ inserted
  -> 8-K 2024-10-07
     ✔ inserted
  -> 8-K 2024-08-26
     ✔ inserted
  -> 8-K 2024-08-22
     ✔ inserted
  -> 8-K 2024-08-14
     ✔ inserted
  -> 10-Q 2024-08-14
     ✔ inserted
  -> 8-K 2024-07-05
     ✔ inserted
  -> 8-K 2024-05-29
     ✔ inserted
  -> 10-Q 2024-05-14
     ✔ inserted
  -> 8-K 2024-05-14
     ✔ inserted
  -> 8-K 2024-04-26
     ✔ inserted
  -> 8-K 2024-04-18
     ✔ inserted
  -> 10-K 2024-04-01
     ✔ inserted
  -> 8-K 2024-03-28
     ✔ inserted
  -> 8-K 2024-03-20
     ✔ inserted
  -> 8-K 2024-03-15
     ✔ inserted
  -> 8-K 2024-03-11
     ✔ inserted
  -> 8-K 2024-03-08
     ✔ inserted
  -> 8-K 2024-03-07
     ✔ inserted
  -> 8-K 2024-03-04
     ✔ inserted
  -> 8-K 2024-01-18
     ✔ inserted
  -> 8-K 2023-12-07
     ✔ inserted
  -> 8-K 2023-11-28
     ✔ inserted
  -> 8-K 2023-11-28
     ✔ inserted
  -> 10-Q 2023-11-14
     ✔ inserted
  -> 8-K 2023-09-08
     ✔ inserted
  -> 10-Q 2023-08-14
     ✔ inserted
  -> 10-Q 2023-05-22
     ✔ inserted
  -> 10-K 2023-03-30
     ✔ inserted
  -> 8-K 2023-03-09
     ✔ inserted
  -> 8-K 2023-03-02
     ✔ inserted
  -> 8-K 2023-03-01
     ✔ inserted
  -> 8-K 2023-01-27
     ✔ inserted
  -> 8-K 2022-11-22
     ✔ inserted
  -> 10-Q 2022-11-14
     ✔ inserted
  -> 10-Q 2022-08-15
     ✔ inserted
  -> 8-K 2022-07-25
     ✔ inserted
  -> 10-Q 2022-05-13
     ✔ inserted
  -> 10-K 2022-03-11
     ✔ inserted
  -> 8-K 2021-11-23
     ✔ inserted
  -> 10-Q 2021-11-12
     ✔ inserted
  -> 10-Q 2021-08-16
     ✔ inserted
  -> 10-Q 2021-07-21
     ✔ inserted
  -> 8-K 2021-06-02
     ✔ inserted
  -> 8-K 2021-04-22
     ✔ inserted
  -> 8-K 2021-03-10
     ✔ inserted
  -> 8-K 2021-03-05
     ✔ inserted
  ✅ Done. Inserted 74.

=== [724/927] RGTI ===

=== CIK=0001838359 ticker=RGTI ===
  Found 90 filings.
  -> 10-Q 2025-11-10
     ✔ inserted
  -> 8-K 2025-11-10
     ✔ inserted
  -> 8-K 2025-09-02
     ✔ inserted
  -> 10-Q 2025-08-12
     ✔ inserted
  -> 8-K 2025-08-12
     ✔ inserted
  -> 8-K 2025-08-12
     ✔ inserted
  -> 8-K 2025-07-18
     ✔ inserted
  -> 8-K 2025-06-11
     ✔ inserted
  -> 8-K 2025-06-11
     ✔ inserted
  -> 8-K 2025-05-30
     ✔ inserted
  -> 10-Q 2025-05-12
     ✔ inserted
  -> 8-K 2025-05-12
     ✔ inserted
  -> 8-K 2025-03-28
     ✔ inserted
  -> 10-K 2025-03-07
     ✔ inserted
  -> 8-K 2025-03-05
     ✔ inserted
  -> 8-K 2025-02-28
     ✔ inserted
  -> 8-K 2025-02-28
     ✔ inserted
  -> 8-K 2025-02-28
     ✔ inserted
  -> 8-K 2024-12-09
     ✔ inserted
  -> 8-K 2024-11-27
     ✔ inserted
  -> 8-K 2024-11-25
     ✔ inserted
  -> 10-Q 2024-11-12
     ✔ inserted
  -> 8-K 2024-11-12
     ✔ inserted
  -> 8-K 2024-11-08
     ✔ inserted
  -> 8-K 2024-11-05
     ✔ inserted
  -> 8-K 2024-09-24
     ✔ inserted
  -> 8-K 2024-09-17
     ✔ inserted
  -> 10-Q 2024-08-08
     ✔ inserted
  -> 8-K 2024-08-08
     ✔ inserted
  -> 8-K 2024-06-24
     ✔ inserted
  -> 8-K 2024-06-20
     ✔ inserted
  -> 10-Q 2024-05-09
     ✔ inserted
  -> 8-K 2024-05-09
     ✔ inserted
  -> 8-K 2024-03-15
     ✔ inserted
  -> 10-K 2024-03-14
     ✔ inserted
  -> 8-K 2024-03-14
     ✔ inserted
  -> 8-K 2024-02-23
     ✔ inserted
  -> 8-K 2024-02-15
     ✔ inserted
  -> 8-K 2024-02-05
     ✔ inserted
  -> 10-Q 2023-11-09
     ✔ inserted
  -> 8-K 2023-11-09
     ✔ inserted
  -> 8-K 2023-10-31
     ✔ inserted
  -> 10-Q 2023-08-10
     ✔ inserted
  -> 8-K 2023-08-10
     ✔ inserted
  -> 8-K 2023-07-13
     ✔ inserted
  -> 8-K 2023-06-21
     ✔ inserted
  -> 10-Q 2023-05-11
     ✔ inserted
  -> 8-K 2023-05-11
     ✔ inserted
  -> 10-K 2023-03-27
     ✔ inserted
  -> 8-K 2023-03-27
     ✔ inserted
  -> 8-K 2023-02-10
     ✔ inserted
  -> 8-K 2023-01-27
     ✔ inserted
  -> 8-K 2022-12-16
     ✔ inserted
  -> 8-K 2022-12-08
     ✔ inserted
  -> 10-Q 2022-11-22
     ✔ inserted
  -> 8-K 2022-11-21
     ✔ inserted
  -> 8-K 2022-11-14
     ✔ inserted
  -> 8-K 2022-11-14
     ✔ inserted
  -> 8-K 2022-11-09
     ✔ inserted
  -> 8-K 2022-10-31
     ✔ inserted
  -> 8-K 2022-09-16
     ✔ inserted
  -> 8-K 2022-09-16
     ✔ inserted
  -> 8-K 2022-08-24
     ✔ inserted
  -> 10-Q 2022-08-12
     ✔ inserted
  -> 8-K 2022-08-11
     ✔ inserted
  -> 8-K 2022-07-06
     ✔ inserted
  -> 8-K 2022-05-25
     ✔ inserted
  -> 8-K 2022-05-19
     ✔ inserted
  -> 10-Q 2022-05-16
     ✔ inserted
  -> 8-K 2022-05-16
     ✔ inserted
  -> 8-K 2022-04-19
     ✔ inserted
  -> 8-K 2022-03-10
     ✔ inserted
  -> 8-K 2022-03-07
     ✔ inserted
  -> 8-K 2022-02-28
     ✔ inserted
  -> 10-K 2022-02-23
     ✔ inserted
  -> 8-K 2022-02-18
     ✔ inserted
  -> 8-K 2022-02-09
     ✔ inserted
  -> 8-K 2022-01-10
     ✔ inserted
  -> 8-K 2022-01-10
     ✔ inserted
  -> 8-K 2021-12-27
     ✔ inserted
  -> 8-K 2021-12-23
     ✔ inserted
  -> 8-K 2021-11-16
     ✔ inserted
  -> 10-Q 2021-11-15
     ✔ inserted
  -> 8-K 2021-10-06
     ✔ inserted
  -> 10-Q 2021-08-13
     ✔ inserted
  -> 10-Q 2021-06-16
     ✔ inserted
  -> 8-K 2021-06-03
     ✔ inserted
  -> 8-K 2021-04-16
     ✔ inserted

In [10]:
print("db name:", db.name)
print("collection full name:", sec_filings.full_name)
print("docs:", sec_filings.count_documents({}))

db name: sec_project
collection full name: sec_project.sec_filings
docs: 65440

In [11]:
print("Total filings stored:", sec_filings.count_documents({}))

sample = sec_filings.find_one(sort=[("_id", -1)])
if sample:
    print("\nSample doc:", sample["ticker"], sample["filing_type"],
          sample["filing_date"], "| used_index =", sample["used_index_page"])
    print("\n--- Raw text preview ---\n")
    print(sample["raw_text"][:1500])

Total filings stored: 65440

Sample doc: LOGC 8-K 2025-08-07 | used_index = False

--- Raw text preview ---

8-K
false
0002064307
0002064307
2025-08-07
2025-08-07
UNITED STATES
SECURITIES AND EXCHANGE COMMISSION
WASHINGTON, D.C. 20549
FORM
8-K
CURRENT REPORT
Pursuant to Section 13 or 15(d) of the Securities Exchange Act of 1934
Date of Report (Date of earliest event reported):
August 07, 2025
ContextLogic Holdings Inc.
(Exact name of Registrant as Specified in Its Charter)
Delaware
333-286589
27-2930953
(State or Other Jurisdiction
of Incorporation)
(Commission File Number)
(IRS Employer
Identification No.)
2648 International Blvd., Ste 115
Oakland
,
California
94601
(Address of Principal Executive Offices)
(Zip Code)
Registrant’s Telephone Number, Including Area Code:
(415)
965-8476
N/A
(Former Name or Former Address, if Changed Since Last Report)
Check the appropriate box below if the Form 8-K filing is intended to simultaneously satisfy the filing obligation of the registrant under any of the following provisions:
☐
Written communications pursuant to Rule 425 under the Securities Act (17 CFR 230.425)
☐
Soliciting material pursuant to Rule 14a-12 under the Exchange Act (17 CFR 240.14a-12)
☐
Pre-commencement communications pursuant to Rule 14d-2(b) under the Exchange Act (17 CFR 240.14d-2(b))
☐
Pre-commencement communications pursuant to Rule 13e-4(c) under the Exchange Act (17 CFR 240.13e-4(c))
Securities registered pursuant to Section 12(b) of the Act:
Indicate by check mark whether the registrant is an emerging growth company as defined in Rule 405 of the Securities Act of 1933

# Create filling_evet table

In [1]:
import psycopg
import pandas as pd
import numpy as np
from pymongo import MongoClient
from datetime import datetime, timedelta
from flask import Flask, request, render_template_string

In [2]:
pg_conn = psycopg.connect(
    host=os.getenv("PGHOST", "localhost"),
    port=os.getenv("PGPORT", "5432"),
    dbname=os.getenv("PGDATABASE", "final"),
    user=os.getenv("PGUSER", "postgres"),
    password=os.getenv("PGPASSWORD")
)
pg_cur = pg_conn.cursor()
print("Connected to PostgreSQL 'final'")

mongo_client = MongoClient("mongodb://localhost:27017")
mongo_db = mongo_client["sec_project"]
sec_filings = mongo_db["sec_filings"]
print("Connected to MongoDB 'sec_project.sec_filings'")

Connected to PostgreSQL 'final'
Connected to MongoDB 'sec_project.sec_filings'

In [3]:
pg_cur.execute("""
    DROP TABLE IF EXISTS filing_event;

    CREATE TABLE filing_event (
        event_id         SERIAL PRIMARY KEY,
        company_id       INTEGER NOT NULL REFERENCES company(company_id),
        event_date       DATE NOT NULL,
        event_type       VARCHAR(32) NOT NULL,   -- FILING_10K / FILING_10Q / FILING_8K / FILING_OTHER
        filing_type      VARCHAR(16),
        filing_accession VARCHAR(64),
        description      TEXT
    );

    CREATE INDEX idx_filing_event_company_date
        ON filing_event(company_id, event_date);
""")
pg_conn.commit()
print("Table 'filing_event' created.")

Table 'filing_event' created.

In [4]:
df_companies = pd.read_sql(
    "SELECT company_id, ticker, company_name FROM company;",
    pg_conn
)
print("Total companies:", len(df_companies))

ticker_to_id = {
    row["ticker"].upper(): int(row["company_id"])
    for _, row in df_companies.iterrows()
}

Total companies: 927

C:\Users\Milan_Chen\AppData\Local\Temp\ipykernel_35284\1538833876.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_companies = pd.read_sql(

In [5]:
def map_event_type(form_type: str) -> str:
   
    if not form_type:
        return "FILING_OTHER"
    ft = form_type.upper()
    if "10-K" in ft:
        return "FILING_10K"
    if "10-Q" in ft:
        return "FILING_10Q"
    if "8-K" in ft:
        return "FILING_8K"
    return "FILING_OTHER"

In [6]:
pg_cur.execute("TRUNCATE TABLE filing_event;")
pg_conn.commit()

inserted = 0
skipped_unknown_ticker = 0

cursor = sec_filings.find({}, {
    "_id": 0,
    "ticker": 1,
    "filing_date": 1,
    "filing_type": 1,
    "accession_number": 1
})

for doc in cursor:
    tk = (doc.get("ticker") or "").upper().strip()
    if not tk:
        continue

    company_id = ticker_to_id.get(tk)
    if company_id is None:
        skipped_unknown_ticker += 1
        continue

    filing_date_raw = doc.get("filing_date")
    if not filing_date_raw:
        continue

    if isinstance(filing_date_raw, str):
        try:
            filing_date = datetime.fromisoformat(filing_date_raw).date()
        except ValueError:
            try:
                filing_date = datetime.strptime(filing_date_raw, "%Y-%m-%d").date()
            except Exception:
                continue
    else:
        filing_date = filing_date_raw.date()

    filing_type = doc.get("filing_type") or ""
    event_type = map_event_type(filing_type)
    accession = doc.get("accession_number") or ""

    pg_cur.execute("""
        INSERT INTO filing_event
            (company_id, event_date, event_type, filing_type, filing_accession, description)
        VALUES
            (%s, %s, %s, %s, %s, %s);
    """, (
        company_id,
        filing_date,
        event_type,
        filing_type,
        accession,
        None
    ))
    inserted += 1

pg_conn.commit()
print("Inserted", inserted, "rows into filing_event.")
print("Skipped because ticker not in company table:", skipped_unknown_ticker)

Inserted 65440 rows into filing_event.
Skipped because ticker not in company table: 0

Calculate the values of a certain company within ±window days around a certain event date
- Daily stock yield return
- Benchmark return of the technology sector
- abnormal_return = return - benchmark
return DataFrame: trade_date, day_offset, return, benchmark_return, abnormal_return

In [7]:
from datetime import timedelta
import pandas as pd

def compute_event_window_returns(company_id, event_date, window=3):

    start_date = event_date - timedelta(days=window + 1)
    end_date   = event_date + timedelta(days=window)

    cur = pg_conn.cursor()

    cur.execute("""
        SELECT trade_date, close
        FROM daily_price
        WHERE company_id = %s
          AND trade_date BETWEEN %s AND %s
        ORDER BY trade_date;
    """, (company_id, start_date, end_date))
    rows = cur.fetchall()
    if len(rows) < 2:
        return None

    df = pd.DataFrame(rows, columns=["trade_date", "close"])
    df["trade_date"] = pd.to_datetime(df["trade_date"])
    df["close"] = df["close"].astype(float)
    df["return"] = df["close"].pct_change()

    cur.execute("""
        SELECT trade_date,
               AVG(ret)::float8 AS benchmark_return
        FROM (
            SELECT
                company_id,
                trade_date,
                close,
                close / NULLIF(
                    LAG(close) OVER (
                        PARTITION BY company_id
                        ORDER BY trade_date
                    ), 0
                ) - 1 AS ret
            FROM daily_price
            WHERE trade_date BETWEEN %s AND %s
        ) t
        WHERE ret IS NOT NULL
        GROUP BY trade_date
        ORDER BY trade_date;
    """, (start_date, end_date))
    bm_rows = cur.fetchall()

    df_bm = pd.DataFrame(bm_rows, columns=["trade_date", "benchmark_return"])
    if not df_bm.empty:
        df_bm["trade_date"] = pd.to_datetime(df_bm["trade_date"])
        df_bm["benchmark_return"] = df_bm["benchmark_return"].astype(float)

    df_merged = df.merge(df_bm, on="trade_date", how="left")
    df_merged["return"] = df_merged["return"].astype(float)
    df_merged["benchmark_return"] = df_merged["benchmark_return"].astype(float)
    df_merged["abnormal_return"] = df_merged["return"] - df_merged["benchmark_return"]

    event_ts = pd.to_datetime(event_date)
    df_merged["day_offset"] = (df_merged["trade_date"] - event_ts).dt.days

    df_win = df_merged[
        (df_merged["day_offset"] >= -window) &
        (df_merged["day_offset"] <= window)
    ].copy()

    return df_win

Take the event from filing_event + company according to the conditions and calculate it
- AR(0)
-CAR (sum of abnormal_return within the window)
- Volatility (standard deviation of abnormal_return within the window)
Add keyword: Search in MongoDB's raw_text and filter for accession
Return list[dict]

In [8]:
def get_event_summaries(ticker=None, date=None, event_type=None, keyword=None, window=3, limit=20):

    valid_accessions = None
    if keyword:
        print(f"Searching MongoDB for keyword: '{keyword}' ...")
        cursor = sec_filings.find(
            {"raw_text": {"$regex": keyword, "$options": "i"}},
            {"accession_number": 1}
        )
        valid_accessions = [doc["accession_number"] for doc in cursor if doc.get("accession_number")]
        print(f"   Found {len(valid_accessions)} matching filings in MongoDB.")
        
        if not valid_accessions:
            return []

    sql = """
        SELECT fe.event_id,
               fe.event_date,
               fe.event_type,
               fe.filing_type,
               fe.filing_accession,
               fe.company_id,
               c.ticker,
               c.company_name
        FROM filing_event fe
        JOIN company c ON fe.company_id = c.company_id
    """
    conds = []
    params = []

    if ticker:
        conds.append("c.ticker = %s")
        params.append(ticker.upper())

    if date:
        conds.append("fe.event_date = %s")
        params.append(date)

    if event_type and event_type != "ALL":
        conds.append("fe.event_type = %s")
        params.append(event_type)

    if valid_accessions is not None:
        conds.append("fe.filing_accession = ANY(%s)")
        params.append(valid_accessions)

    if conds:
        sql += " WHERE " + " AND ".join(conds)

    sql += " ORDER BY fe.event_date DESC LIMIT %s;"
    params.append(limit)

    pg_cur.execute(sql, params)
    rows = pg_cur.fetchall()

    results = []
    for (event_id, event_date, ev_type, filing_type, accession,
         company_id, tk, company_name) in rows:

        df_win = compute_event_window_returns(company_id, event_date, window)
        if df_win is None or df_win.empty:
            ar0 = None
            car = None
            vol = None
        else:
            row0 = df_win[df_win["day_offset"] == 0]
            if not row0.empty and not pd.isna(row0["abnormal_return"].iloc[0]):
                ar0 = float(row0["abnormal_return"].iloc[0])
            else:
                ar0 = None

            car = float(df_win["abnormal_return"].sum()) if "abnormal_return" in df_win else None

            vol = float(df_win["abnormal_return"].std(ddof=1)) if "abnormal_return" in df_win else None

        sec_url = ""
        if accession:
            doc = sec_filings.find_one(
                {"accession_number": accession},
                {"_id": 0, "source_main": 1}
            )
            if doc and doc.get("source_main"):
                sec_url = doc["source_main"]

        if not sec_url:
            doc = sec_filings.find_one(
                {"ticker": tk.upper(), "filing_date": event_date.isoformat()},
                {"_id": 0, "source_main": 1}
            )
            if doc and doc.get("source_main"):
                sec_url = doc["source_main"]

        results.append({
            "event_id": event_id,
            "ticker": tk,
            "company_name": company_name,
            "event_date": event_date.isoformat(),
            "event_type": ev_type,
            "filing_type": filing_type,
            "ar0": ar0,
            "car": car,
            "vol": vol,
            "sec_url": sec_url,
        })

    return results

In [9]:
PAGE_TEMPLATE = """
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Event Study Dashboard</title>
    <style>
      body { font-family: Arial, sans-serif; background-color: #fafafa; }
      h1 { text-align: center; margin-top: 20px; }

      .panel {
        border-radius: 8px;
        padding: 16px 24px;
        margin: 16px auto;
        width: 900px;
        background-color: #fffbe6; /* light yellow */
        box-shadow: 0 0 4px rgba(0,0,0,0.1);
      }
      .panel-title {
        text-align: center;
        font-weight: bold;
        margin-bottom: 10px;
      }
      .input-row {
        display: flex;
        gap: 20px;
        justify-content: center;
        margin-top: 8px;
        flex-wrap: wrap;
      }
      .input-box {
        background-color: #f5f0ff;
        padding: 8px 12px;
        border-radius: 6px;
        border: 1px solid #d0c4ff;
      }
      label {
        margin-right: 4px;
        font-size: 14px;
      }
      input[type="text"], input[type="number"], input[type="date"], select {
        border: none;
        border-bottom: 1px solid #888;
        background-color: transparent;
        outline: none;
        padding: 2px 4px;
      }
      .buttons {
        display: flex;
        justify-content: center;
        gap: 40px;
        margin-top: 10px;
      }
      .btn-main {
        padding: 8px 24px;
        border-radius: 6px;
        border: none;
        font-size: 16px;
        cursor: pointer;
      }
      .btn-exec {
        background-color: #28a745;
        color: #fff;
      }
      .btn-reset {
        background-color: #f0f0f0;
        color: #333;
      }

      table {
        border-collapse: collapse;
        width: 100%;
        margin-top: 10px;
      }
      th, td {
        border: 1px solid #aaa;
        padding: 4px 6px;
        font-size: 13px;
        text-align: center;
      }
      th {
        background-color: #f0f0f0;
      }
      .sec-link a {
        color: #3366cc;
        text-decoration: none;
      }
      .sec-link a:hover {
        text-decoration: underline;
      }
      .no-result {
        font-size: 13px;
        color: #666;
        text-align: center;
        margin-top: 10px;
      }
    </style>
  </head>
  <body>
    <h1>Event Study Dashboard</h1>

    <!-- INPUT PANEL -->
    <form method="get" action="/">
      <div class="panel">
        <div class="panel-title">Input Panel</div>
        <div class="input-row">
          <div class="input-box">
            <label>Ticker:</label>
            <input type="text" name="ticker" value="{{ ticker }}" placeholder="e.g. AAPL">
          </div>
          <div class="input-box">
            <label>Date:</label>
            <!-- HTML5 date input with calendar -->
            <input type="date" name="date" value="{{ date }}">
          </div>
          <div class="input-box">
            <label>Event Type:</label>
            <select name="event_type">
              <option value="ALL" {% if event_type == "ALL" %}selected{% endif %}>All Types</option>
              <option value="FILING_10K" {% if event_type == "FILING_10K" %}selected{% endif %}>10-K</option>
              <option value="FILING_10Q" {% if event_type == "FILING_10Q" %}selected{% endif %}>10-Q</option>
              <option value="FILING_8K" {% if event_type == "FILING_8K" %}selected{% endif %}>8-K</option>
              <option value="FILING_OTHER" {% if event_type == "FILING_OTHER" %}selected{% endif %}>Other</option>
            </select>
          </div>
          <div class="input-box">
            <label>Window (days):</label>
            <input type="number" name="window" min="1" max="30" value="{{ window }}">
          </div>
        </div>
        
        <!-- New Row for Keyword Search -->
        <div class="input-row">
            <div class="input-box" style="width: 60%;">
                <label>Keyword (MongoDB Search):</label>
                <input type="text" name="keyword" value="{{ keyword }}" placeholder="Search in filing text..." style="width: 80%;">
            </div>
        </div>
      </div>

      <!-- ACTION PANEL -->
      <div class="panel">
        <div class="panel-title">Actions</div>
        <div class="buttons">
          <button class="btn-main btn-exec" type="submit">Run Study</button>
          <button class="btn-main btn-reset" type="button" onclick="window.location='/'">Reset</button>
        </div>
      </div>
    </form>

    <!-- RESULT PANEL -->
    <div class="panel">
      <div class="panel-title">Results</div>
      {% if events and events|length > 0 %}
        <table>
          <tr>
            <th>Ticker</th>
            <th>Date</th>
            <th>Type</th>
            <th>AR(0)</th>
            <th>CAR</th>
            <th>Volatility</th>
            <th>Action</th>
          </tr>
          {% for e in events %}
          <tr>
            <td>{{ e.ticker }}</td>
            <td>{{ e.event_date }}</td>
            <td>{{ e.filing_type or e.event_type }}</td>
            <td>
              {% if e.ar0 is not none %}
                {{ "%.2f"|format(e.ar0 * 100) }}%
              {% else %}
                -
              {% endif %}
            </td>
            <td>
              {% if e.car is not none %}
                {{ "%.2f"|format(e.car * 100) }}%
              {% else %}
                -
              {% endif %}
            </td>
            <td>
              {% if e.vol is not none %}
                {{ "%.2f"|format(e.vol * 100) }}%
              {% else %}
                -
              {% endif %}
            </td>
            <td class="sec-link">
              {% if e.sec_url %}
                <a href="{{ e.sec_url }}" target="_blank">View SEC Filing</a>
              {% else %}
                No link
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </table>
      {% else %}
        <div class="no-result">
          No events found for the current filters.
          {% if keyword %}
            <br>(Keyword search '{{ keyword }}' returned no matches in MongoDB)
          {% endif %}
        </div>
      {% endif %}
    </div>
  </body>
</html>
"""

In [10]:
app = Flask(__name__)

In [11]:
@app.route("/", methods=["GET"])
def index():
    ticker = (request.args.get("ticker") or "").strip().upper()
    date_str = (request.args.get("date") or "").strip()
    event_type = request.args.get("event_type", "ALL")
    window_str = request.args.get("window", "3")
    keyword = (request.args.get("keyword") or "").strip()

    try:
        window = int(window_str)
        if window < 1:
            window = 1
        if window > 30:
            window = 30
    except ValueError:
        window = 3

    date_val = None
    if date_str:
        try:
            date_val = datetime.strptime(date_str, "%Y-%m-%d").date()
        except ValueError:
            date_val = None

    events = get_event_summaries(
        ticker=ticker if ticker else None,
        date=date_val,
        event_type=event_type,
        keyword=keyword if keyword else None,
        window=window,
        limit=20
    )

    return render_template_string(
        PAGE_TEMPLATE,
        ticker=ticker,
        date=date_str,
        event_type=event_type,
        window=window,
        keyword=keyword,
        events=events
    )

In [ ]:
app.run(debug=True, use_reloader=False)

 * Serving Flask app '__main__'
 * Debug mode: on

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [06/Dec/2025 16:57:30] "GET / HTTP/1.1" 200 -

# Data Size Check

In [12]:
stats = db.command("collstats", "sec_filings")

print("=== MongoDB Collection Size ===")
print(f"Documents count         : {stats['count']}")
print(f"Raw data size           : {stats['size'] / 1024**3:.3f} GB")
print(f"Actual storage size     : {stats['storageSize'] / 1024**3:.3f} GB")
print(f"Total index size        : {stats['totalIndexSize'] / 1024**3:.3f} GB")

=== MongoDB Collection Size ===
Documents count         : 65440
Raw data size           : 3.850 GB
Actual storage size     : 1.716 GB
Total index size        : 1.276 GB

In [2]:
conn = psycopg.connect(
    host=os.getenv("PGHOST", "local"),
    port=os.getenv("PGPORT", "5432"),
    dbname=os.getenv("PGDATABASE", "final"),
    user=os.getenv("PGUSER", "postgres"),
    password=os.getenv("PGPASSWORD")
)
cur = conn.cursor()

tables_to_show = ["daily_price", "filing_event", "company"]

cur.execute("""
    SELECT 
        relname AS table_name,
        pg_size_pretty(pg_total_relation_size(relid)) AS total_size
    FROM pg_catalog.pg_statio_user_tables
    ORDER BY pg_total_relation_size(relid) DESC;
""")

print("\nSize of selected tables:")
for table_name, size in cur.fetchall():
    if table_name in tables_to_show:
        print(f"{table_name:20s} {size}")

Size of selected tables:
daily_price          162 MB
filing_event         8168 kB
company              280 kB